/**
 * Check run annotation fetcher.
 *
 * Fetches annotations from GitHub check runs.
 */

import { createLogger, GITHUB_CONTEXT_LIMITS } from "@kenchi/shared";
import { getOctokit } from "../githubService.js";
import type { CheckRunAnnotation } from "./types.js";

const logger = createLogger("github-app");

/**
 * Fetch check run annotations from GitHub.
 *
 * Annotations include file-level error and warning messages
 * generated by the check run (e.g., lint errors, type errors).
 *
 * @param installationId - GitHub App installation ID
 * @param owner - Repository owner
 * @param repo - Repository name
 * @param checkRunId - Check run ID
 * @returns Array of check run annotations
 */
export const fetchCheckRunAnnotations = async (
  installationId: number,
  owner: string,
  repo: string,
  checkRunId: number
): Promise<CheckRunAnnotation[]> => {
  try {
    const octokit = await getOctokit(installationId);

    // Use listAnnotations API to get annotations for a check run
    const { data: annotations } = await octokit.rest.checks.listAnnotations({
      owner,
      repo,
      check_run_id: checkRunId,
      per_page: GITHUB_CONTEXT_LIMITS.MAX_ANNOTATIONS,
    });

    const result: CheckRunAnnotation[] = annotations
      .filter((ann) => ann.message) // Only include annotations with messages
      .map((ann) => ({
        path: ann.path,
        startLine: ann.start_line,
        endLine: ann.end_line,
        level: ann.annotation_level as "notice" | "warning" | "failure",
        message: ann.message as string,
        title: ann.title || undefined,
      }));

    logger.info("Fetched check run annotations", {
      checkRunId,
      count: result.length,
    });

    return result;
  } catch (error) {
    logger.warn("Failed to fetch check run annotations", {
      checkRunId,
      error: error instanceof Error ? error.message : "Unknown error",
    });
    return [];
  }
};
