/**
 * Check run annotation fetcher.
 *
 * Fetches annotations from GitHub check runs.
 */

import {
  createLogger,
  GITHUB_CONTEXT_LIMITS,
  getErrorMessage,
  getOrFetchCheckAnnotations,
} from "@kenchi/shared";
import { getOctokit } from "../githubService.js";
import type { CheckRunAnnotation } from "./types.js";

const logger = createLogger("github-app");

/**
 * Fetch check run annotations from GitHub with caching.
 *
 * Annotations include file-level error and warning messages
 * generated by the check run (e.g., lint errors, type errors).
 *
 * @param installationId - GitHub App installation ID
 * @param owner - Repository owner
 * @param repo - Repository name
 * @param checkRunId - Check run ID
 * @returns Array of check run annotations
 */
export const fetchCheckRunAnnotations = async (
  installationId: number,
  owner: string,
  repo: string,
  checkRunId: number
): Promise<CheckRunAnnotation[]> => {
  try {
    const cachedAnnotations = await getOrFetchCheckAnnotations(
      owner,
      repo,
      checkRunId,
      async () => {
        const octokit = await getOctokit(installationId);

        // Use listAnnotations API to get annotations for a check run
        const { data: annotations } = await octokit.rest.checks.listAnnotations({
          owner,
          repo,
          check_run_id: checkRunId,
          per_page: GITHUB_CONTEXT_LIMITS.MAX_ANNOTATIONS,
        });

        return annotations
          .filter((annotation) => annotation.message && annotation.annotation_level)
          .map((annotation) => ({
            path: annotation.path,
            startLine: annotation.start_line,
            endLine: annotation.end_line,
            annotationLevel: annotation.annotation_level as string,
            message: annotation.message as string,
            title: annotation.title || undefined,
          }));
      }
    );

    // Convert cached format to CheckRunAnnotation format
    const result: CheckRunAnnotation[] = cachedAnnotations.map((annotation) => ({
      path: annotation.path,
      startLine: annotation.startLine,
      endLine: annotation.endLine,
      level: annotation.annotationLevel as "notice" | "warning" | "failure",
      message: annotation.message,
      title: annotation.title,
    }));

    logger.info("Fetched check run annotations", {
      checkRunId,
      count: result.length,
    });

    return result;
  } catch (error) {
    logger.warn("Failed to fetch check run annotations", {
      checkRunId,
      error: getErrorMessage(error),
    });
    return [];
  }
};
