/**
 * Data Export Constants
 *
 * SQL queries and configuration for data export operations.
 *
 * @module constants/dataExport
 */

// ==================== Default Values ====================

export const DATA_EXPORT_DEFAULTS = {
  /** Default limit for listing export jobs. */
  DEFAULT_LIST_LIMIT: 50,
} as const;

// ==================== Status Values ====================

export const DATA_EXPORT_STATUS = {
  PENDING: "pending",
  PROCESSING: "processing",
  COMPLETED: "completed",
  FAILED: "failed",
  EXPIRED: "expired",
} as const;

// ==================== SQL Queries ====================

export const DATA_EXPORT_QUERIES = {
  /** ID is auto-generated by gen_random_uuid(). */
  INSERT: `
    INSERT INTO data_exports (tenant_id, status, requested_by)
    VALUES ($1, $2, $3)
    RETURNING *
  `,

  FIND_BY_ID: `
    SELECT * FROM data_exports
    WHERE id = $1 AND tenant_id = $2
  `,

  UPDATE_STATUS: `
    UPDATE data_exports
    SET status = $1,
        file_path = COALESCE($2, file_path),
        download_url = COALESCE($3, download_url),
        expires_at = COALESCE($4, expires_at),
        completed_at = CASE WHEN $1 IN ('completed', 'failed') THEN NOW() ELSE completed_at END,
        error_message = COALESCE($5, error_message)
    WHERE id = $6 AND tenant_id = $7
    RETURNING *
  `,

  LIST_BY_TENANT: `
    SELECT * FROM data_exports
    WHERE tenant_id = $1
    ORDER BY created_at DESC
    LIMIT $2
  `,
} as const;
