/**
 * Centralized constants barrel file.
 * Re-exports all constants from their respective modules.
 */

// Confidence scoring constants
export {
  CONFIDENCE_THRESHOLDS,
  BASE_CONFIDENCE_SCORES,
  DEFAULT_CONFIDENCE_THRESHOLD,
  PLACEHOLDER_CONFIDENCE_SCORE,
  UNCERTAINTY_PENALTIES,
  ALIGNMENT_ADJUSTMENTS,
  COMPLETENESS_ADJUSTMENTS,
  VALIDATION_ADJUSTMENTS,
  CONSISTENCY_ADJUSTMENTS,
  SIMILARITY_THRESHOLDS,
  RELEVANCE_THRESHOLDS,
  MIN_LENGTHS,
  MIN_ACTIONS_FOR_BONUS,
  CONFIDENCE_MESSAGES,
  CONFIDENCE_DISPLAY_LABELS,
  CONTEXT_CONFIDENCE_ADJUSTMENTS,
  CONFIDENCE_DISPLAY_THRESHOLDS,
  CONFIDENCE_LEVEL_THRESHOLDS,
  type ConfidenceRange,
  type DerivedConfidenceLevel,
} from "./confidence.js";

// HTTP and error constants
export {
  HTTP_STATUS,
  ERROR_CODES,
  DEFAULT_ERROR_MESSAGES,
  VALIDATION_MESSAGES,
  RATE_LIMIT_MESSAGES,
  EXTERNAL_SERVICE_NAMES,
  SERVICE_NAMES,
  SERVICE_VERSIONS,
  EXPRESS_CONFIG,
  SERVER_TIMEOUTS,
} from "./http.js";

// Event constants
export {
  EVENT_TYPES,
  EVENT_SOURCES,
  EVENT_SEVERITY,
  LOG_LEVELS,
  EVIDENCE_SOURCES,
  EVENT_DEFAULTS,
  type EventType,
  type EventSource,
  type EventSeverity,
  type LogLevel,
  type EvidenceSource,
} from "./events.js";

// Time, ports, and rate limiting
export { TIME_CONSTANTS, SERVICE_PORTS, RATE_LIMIT_CONSTANTS } from "./time.js";

// UI and display constants
export {
  UI_CONFIDENCE_THRESHOLDS,
  UI_CONSTANTS,
  UI_EMOJI,
  PRIORITY_EMOJI_MAP,
  DOC_TYPE_EMOJI_MAP,
  NUMBER_EMOJI_LIST,
  PRIORITY_ORDER,
  PRIORITY_ORDER_DEFAULT,
  ANNOTATION_LEVEL_EMOJI_MAP,
  DEPENDENCY_EMOJI_MAP,
  CONFIDENCE_BADGE_THRESHOLDS,
  SLACK_COLORS,
  SLACK_STATUS_EMOJI,
  PRIORITY_EMOJI,
  VALID_SAFETY_LEVELS,
} from "./ui.js";

// Validation constants
export {
  EMAIL_REGEX,
  SLACK_CHANNEL_ID_PATTERN,
  DEFAULT_VALIDATION_ERROR_MESSAGE,
  DANGEROUS_KEYWORDS,
  DANGEROUS_KEYWORDS_PATTERN,
} from "./validation.js";

// Safety analysis constants
export {
  UNCERTAINTY_PATTERNS,
  METRIC_KEYWORDS,
  INVALID_CAUSE_KEYWORDS,
  RELEVANCE_RULES,
  AUTO_APPROVABLE_SAFETY_LEVELS,
  SAFETY_MESSAGES,
  type UncertaintyPattern,
  type RelevanceRule,
} from "./safety.js";

// GitHub constants
export {
  GITHUB_CONTEXT_LIMITS,
  GITHUB_SIGNATURE,
  GITHUB_COMMENT_DISPLAY,
  FILE_PATH_VALIDATION,
  LOG_PARSING_LIMITS,
  TRUNCATION_WINDOW_CONFIG,
  EXCLUDED_PATH_PATTERNS,
  ERROR_INDICATORS,
  CI_FAILURE_PATTERNS,
  CI_FAILURE_TIER1_PATTERNS,
  CI_FAILURE_TIER2_PATTERNS,
  CI_FAILURE_TIER3_PATTERNS,
  CI_FAILURE_TIER4_PATTERNS,
  FILE_REFERENCE_PATTERNS,
  CI_FAILURE_DISPLAY,
  GITHUB_STATUS,
  GITHUB_CONCLUSION,
  GITHUB_ANNOTATION_LEVEL,
  GITHUB_ANNOTATION_LIMITS,
  TEXT_SANITIZATION_PATTERNS,
  SHORT_COMMIT_SHA_LENGTH,
  PR_CONTEXT_CORRELATION,
  SKIP_DIRECTORY_PREFIXES,
  ABSOLUTE_PATH_SKIP_DIRS,
  ABSOLUTE_PATH_PATTERN,
  ACTION_REVIEW_PATTERNS,
} from "./github.js";

// Evidence parsing constants
export {
  ERROR_SECTION_HEADINGS,
  SECTION_SOURCE_OVERRIDES,
  EVIDENCE_LOG_TIMING,
  EVIDENCE_TEXT_LIMITS,
} from "./evidence.js";

// OpenAI and text processing constants
export {
  OPENAI_DEFAULTS,
  OPENAI_CONSTANTS,
  EVIDENCE_TRUNCATION,
  MATCHING_CONFIG,
  SHA_PATTERN,
  SHA_PATTERN_SINGLE,
  QUOTED_TEXT_PATTERN,
  LOG_NORMALIZATION_PATTERNS,
  OPENAI_MESSAGES,
  TENANT_PROMPT_LIMITS,
  MODEL_VERSIONING,
  DATASET_THRESHOLDS,
  FINE_TUNING_CONFIG,
  FINE_TUNING_STATUS,
  FINE_TUNING_READINESS,
  FINE_TUNING_SCHEDULER,
  type FineTuningStatus,
} from "./openai.js";

// RAG constants
export {
  EMBEDDING_CONFIG,
  CHUNKING_CONFIG,
  VECTOR_SIMILARITY_THRESHOLDS,
  KNOWLEDGE_DOC_TYPES,
  AUTO_DETECT_RELATIONSHIP_DOC_TYPES,
  RELATIONSHIP_TYPES,
  MULTI_HOP_CONFIG,
  RELATIONSHIP_DETECTION_CONFIG,
  EXTERNAL_SOURCE_TYPES,
  TECH_STACK_TAGS,
  EXTERNAL_SOURCE_CONFIG,
  TTL_POLICIES,
  DRIFT_DETECTION_THRESHOLDS,
  RAG_JOB_INTERVALS,
  RAG_EVALUATION_CONFIG,
  RAG_TEST_CASE_CONFIG,
  EMBEDDING_TIERS,
  COST_CONTROL_CONFIG,
  RAG_METRIC_TYPES,
  type KnowledgeDocType,
  type RelationshipType,
  type ExternalSourceType,
  type TechStackTag,
  type EmbeddingTierName,
  type RAGMetricType,
  type EvidenceKnowledgeDocType,
  RAG_TO_EVIDENCE_DOC_TYPE_MAP,
} from "./ragConstants.js";

// Secret detection constants
export {
  REDACTION_PLACEHOLDER,
  REDACTION_DEFAULTS,
  SECRET_PATTERNS,
  FORBIDDEN_FIELDS,
  type SecretPattern,
} from "./secrets.js";

// Slack-specific constants
export {
  SLACK_VERIFICATION,
  SLACK_API_LIMITS,
  SOCKET_MODE_ERROR_PATTERNS,
  isSocketModeDisconnectError,
} from "./slack.js";

// Database constants
export { DATABASE_POOL_DEFAULTS, QUERY_LOGGING, TRANSACTION_COMMANDS } from "./database.js";

// Action executor constants
export {
  ACTION_MESSAGES,
  ACTION_STORE_CONFIG,
  ACTION_TOKEN_CONFIG,
  ACTION_CHAR_SETS,
} from "./actions.js";

// Tenant constants
export {
  TENANT_STATUS,
  AUDIT_ACTIONS,
  AUDIT_DEFAULTS,
  TENANT_DEFAULTS,
  RAG_BUDGET_DEFAULTS,
  TENANT_QUERIES,
  AUDIT_QUERIES,
  TENANT_FIELD_MAP,
  AUDIT_FIELD_MAP,
} from "./tenant.js";

// Action proposal constants
export {
  ACTION_PROPOSAL_DEFAULTS,
  ACTION_PROPOSAL_QUERIES,
  VALID_ACTION_PROPOSAL_STATUSES,
  MIN_STATS_WINDOW_MINUTES,
} from "./actionProposal.js";

// Analysis constants
export { ANALYSIS_DEFAULTS, ANALYSIS_QUERIES } from "./analysis.js";

// Cost tracking constants
export { COST_TRACKING_DEFAULTS, COST_TRACKING_QUERIES } from "./costTracking.js";

// Core module constants
export {
  LOGGER_DEFAULTS,
  CONFIG_DEFAULTS,
  VALID_NODE_ENVS,
  PARSE_INT_RADIX,
  HEX_RADIX,
  HEX_BYTE_WIDTH,
  HTTP_RESILIENCE_DEFAULTS,
  RETRYABLE_HTTP_STATUS_CODES,
  RETRYABLE_NETWORK_ERRORS,
  ID_GENERATION,
} from "./core.js";

// LLM concurrency constants
export { LLM_CONCURRENCY_DEFAULTS } from "./llmConcurrency.js";

// Redis constants
export {
  REDIS_STATUS,
  REDIS_RESPONSES,
  REDIS_LIST_OPS,
  REDIS_TTL_VALUES,
  REDIS_SCAN,
  REDIS_TIMEOUTS,
  REDIS_CONNECTION_DEFAULTS,
  RETRYABLE_ERROR_PATTERNS,
  SLACK_RETRYABLE_ERROR_PATTERNS,
  CACHE_TTL_SECONDS,
  REDIS_KEY_PREFIXES,
  CACHE_KEY_STRUCTURE,
  CACHE_NAMESPACES,
  ANALYSIS_HASH_ALGORITHM,
  ANALYSIS_CACHE_VERSION,
  CACHE_KEY_SEGMENT_INDICES,
  MIN_CACHE_KEY_SEGMENTS,
  CACHE_KEY_SEPARATOR,
  REPO_SLASH_REPLACEMENT,
  CHECK_NAME_WHITESPACE_PATTERN,
  REDIS_READY_STATUS,
  REDIS_KEY_EXISTS,
  CACHE_TTL_ERROR_DEFAULT,
  QUEUE_WORKER_DEFAULTS,
  AGGREGATION_DEFAULTS,
  AGGREGATION_KEY_PATTERN,
  AGGREGATION_METADATA_FIELDS,
  DISPLAY_DEFAULTS,
  RETRY_DEFAULTS,
  QUEUE_CONFIG,
  QUEUE_RETRY_CONFIG,
  QUEUE_VISIBILITY_TIMEOUT,
  QUEUE_NAMES,
  PUBSUB_CHANNELS,
  type CacheNamespace,
} from "./redis.js";

// API service constants
export {
  API_ROUTES,
  SWAGGER_ROUTES,
  RATE_LIMIT_SKIP_PATHS,
  HEALTH_STATUS,
  MEMORY_THRESHOLDS,
  API_RESPONSE_STATUS,
  API_MESSAGES,
  API_REDIS_PREFIXES,
  API_LOG_CONTEXT,
  API_LOG_LIMITS,
  API_REQUEST_FIELDS,
  shouldSkipRateLimit,
  type HealthStatus,
  type ApiResponseStatus,
} from "./api.js";

// Slack Bot service constants
export {
  SLACK_BOT_RATE_LIMITS,
  SLACK_BOT_TIMEOUTS,
  SLACK_BOT_DB_CONFIG,
  SLACK_MODAL_CALLBACKS,
  SLACK_ACTION_IDS,
  SLACK_ACTION_PATTERNS,
  SLACK_BLOCK_IDS,
  SLACK_OAUTH_TIMING,
  SLACK_OAUTH_SCOPES,
  SLACK_OAUTH_SCOPES_STRING,
  PRIORITY_NUMERIC_MAP,
  SLACK_BOT_MESSAGES,
  SLACK_BOT_HEALTH_PATH,
  shouldSkipSlackBotRateLimit,
  SLACK_CLIENT_CACHE,
  MESSAGE_STORE_CONFIG,
  RESOLUTION_SERVICE_CONFIG,
  ANALYSIS_CONTEXT_STORE_CONFIG,
  QA_CONFIG,
  QA_QUESTION_PATTERNS,
  QA_ACTION_IDS,
  QA_MESSAGES,
  isQuestionLike,
  DOC_INGESTION_CONFIG,
  DOC_INGESTION_PATTERNS,
  DOC_INGESTION_MESSAGES,
  isDocIngestionRequest,
  SLACK_UI_ERROR_MESSAGES,
  DOC_INGESTION_ERROR_CODES,
  type NumericPriority,
  type StringPriority,
} from "./slackBot.js";

// GitHub App service constants
export {
  GITHUB_APP_RATE_LIMITS,
  GITHUB_APP_HEALTH_PATHS,
  shouldSkipGitHubAppRateLimit,
  GITHUB_APP_TIMEOUTS,
  GITHUB_APP_DB_CONFIG,
  GITHUB_SETUP_CONFIG,
  GITHUB_APP_MESSAGES,
  KENCHI_BRANDING,
  GITHUB_COMMENT_TEMPLATES,
  SLACK_FAILURE_TEMPLATES,
  FORMATTER_DISPLAY_LIMITS,
  CONFIDENCE_DESCRIPTIONS,
  CATEGORY_EMOJI,
  MESSAGE_VARIANT_CONFIG,
  GITHUB_RETRY_CONFIG,
  GITHUB_PAGINATION,
  CONTEXT_FETCH_CONFIG,
  type MessageVariant,
} from "./githubApp.js";

// Passive learning constants
export {
  PASSIVE_LEARNING_TIME,
  FIX_COMMENT_PATTERNS,
  FIX_COMMENT_EXCLUSIONS,
  PR_FIX_COMMENT_CONFIG,
  SLACK_RESOLUTION_CONFIG,
  ANALYSIS_LESSON_CONFIG,
  KNOWLEDGE_QUALITY_WEIGHTS,
  SOURCE_RELIABILITY_SCORES,
  KNOWLEDGE_GC_CONFIG,
  FEEDBACK_URL_CONFIG,
} from "./passiveLearning.js";

// Cause extraction pattern constants
export {
  CAUSE_EXTRACTION_LIMITS,
  USELESS_CAUSE_PATTERNS,
  CAUSE_SIGNAL_WEIGHTS,
  CAUSE_WEAKNESS_WEIGHTS,
  TEST_FILE_PATTERNS,
} from "./causePatterns.js";

// Chunking pipeline constants
export {
  TOKEN_ESTIMATION,
  CHUNKING_DEFAULTS,
  PROTECTED_ZONE_CONFIG,
  PROTECTED_ZONE_PATTERNS,
  NATURAL_BOUNDARY_PATTERNS,
  ASSERTION_HASH_CONFIG,
  EXTRACTION_DEFAULTS,
  ARTIFACT_TYPES,
  ARTIFACT_PRIORITY_WEIGHTS,
  ARTIFACT_SEVERITY,
  ARTIFACT_CONFIDENCE,
  CHUNKING_AGGREGATION_DEFAULTS,
  PRIMARY_FAILURE_CONFIG,
  CAUSALITY_TYPE_ORDER,
  STACKTRACE_INDICATORS,
  DEGRADED_MODE_CONFIG,
  DEGRADED_MODE_PROMPT,
  CI_PLATFORMS,
  CI_PLATFORM_DETECTION_PATTERNS,
  LINE_COLLAPSE_CONFIG,
  LINE_NUMBER_CONFIG,
  PERCENTAGE_CONFIG,
  PROGRESS_INDICATOR_PATTERNS,
  BOUNDARY_TYPES,
  PROTECTED_ZONE_TYPES,
  EVIDENCE_ID_PATTERN,
  TRUNCATION_MARKER,
  ANCHOR_TIERS,
  TEST_SUMMARY_PATTERNS,
  TEST_FRAMEWORK_CONFIDENCE,
  type ArtifactType,
  type ArtifactSeverity,
  type ArtifactConfidence,
  type BoundaryType,
  type ProtectedZoneType,
  type CIPlatformType,
} from "./chunkingPipeline.js";

// Diff chunk constants
export { DIFF_CHUNK_DEFAULTS, DIFF_CHUNK_QUERIES } from "./diffChunk.js";

// External source constants
export { EXTERNAL_SOURCE_DEFAULTS, EXTERNAL_SOURCE_QUERIES } from "./externalSource.js";

// Feedback constants
export { FEEDBACK_DEFAULTS, FEEDBACK_QUERIES } from "./feedback.js";

// Dataset extractor constants
export { EXTRACTION_QUERIES, VALIDATION_CHECKS } from "./datasetExtractor.js";

// Knowledge document hit tracking constants
export { HIT_TRACKING_DEFAULTS, HIT_TRACKING_QUERIES } from "./knowledgeDocHitTracking.js";

// Knowledge document repository constants
export { KNOWLEDGE_DOC_DEFAULTS, KNOWLEDGE_DOC_QUERIES } from "./knowledgeDocRepository.js";

// Metrics history constants
export { METRICS_HISTORY_DEFAULTS, METRICS_HISTORY_QUERIES } from "./metricsHistory.js";

// Model version constants
export { MODEL_VERSION_DEFAULTS, MODEL_VERSION_QUERIES } from "./modelVersion.js";

// Relationship constants
export { RELATIONSHIP_DEFAULTS, RELATIONSHIP_QUERIES } from "./relationship.js";

// Test case constants
export { TEST_CASE_DEFAULTS, TEST_CASE_QUERIES } from "./testCase.js";

// Repository channel constants
export { REPOSITORY_CHANNEL_QUERIES } from "./repositoryChannel.js";
