/**
 * Centralized constants barrel file.
 * Re-exports all constants from their respective modules.
 */

// Confidence scoring constants
export {
  CONFIDENCE_THRESHOLDS,
  BASE_CONFIDENCE_SCORES,
  DEFAULT_CONFIDENCE_THRESHOLD,
  PLACEHOLDER_CONFIDENCE_SCORE,
  UNCERTAINTY_PENALTIES,
  ALIGNMENT_ADJUSTMENTS,
  COMPLETENESS_ADJUSTMENTS,
  VALIDATION_ADJUSTMENTS,
  CONSISTENCY_ADJUSTMENTS,
  SIMILARITY_THRESHOLDS,
  RELEVANCE_THRESHOLDS,
  MIN_LENGTHS,
  MIN_ACTIONS_FOR_BONUS,
  CONFIDENCE_MESSAGES,
  type ConfidenceRange,
} from "./confidence.js";

// HTTP and error constants
export {
  HTTP_STATUS,
  ERROR_CODES,
  DEFAULT_ERROR_MESSAGES,
  VALIDATION_MESSAGES,
  RATE_LIMIT_MESSAGES,
  EXTERNAL_SERVICE_NAMES,
  SERVICE_NAMES,
  SERVICE_VERSIONS,
  EXPRESS_CONFIG,
  SERVER_TIMEOUTS,
} from "./http.js";

// Event constants
export {
  EVENT_TYPES,
  EVENT_SOURCES,
  EVENT_SEVERITY,
  LOG_LEVELS,
  EVIDENCE_SOURCES,
  EVENT_DEFAULTS,
  type EventType,
  type EventSource,
  type EventSeverity,
  type LogLevel,
  type EvidenceSource,
} from "./events.js";

// Time, ports, and rate limiting
export { TIME_CONSTANTS, SERVICE_PORTS, RATE_LIMIT_CONSTANTS } from "./time.js";

// UI and display constants
export {
  UI_CONFIDENCE_THRESHOLDS,
  UI_CONSTANTS,
  UI_EMOJI,
  PRIORITY_EMOJI_MAP,
  DOC_TYPE_EMOJI_MAP,
  NUMBER_EMOJI_LIST,
  PRIORITY_ORDER,
  PRIORITY_ORDER_DEFAULT,
  ANNOTATION_LEVEL_EMOJI_MAP,
  DEPENDENCY_EMOJI_MAP,
  CONFIDENCE_BADGE_THRESHOLDS,
  SLACK_COLORS,
  SLACK_STATUS_EMOJI,
  PRIORITY_EMOJI,
  VALID_SAFETY_LEVELS,
} from "./ui.js";

// Validation constants
export {
  EMAIL_REGEX,
  SLACK_CHANNEL_ID_PATTERN,
  DEFAULT_VALIDATION_ERROR_MESSAGE,
  DANGEROUS_KEYWORDS,
  DANGEROUS_KEYWORDS_PATTERN,
} from "./validation.js";

// Safety analysis constants
export {
  UNCERTAINTY_PATTERNS,
  METRIC_KEYWORDS,
  INVALID_CAUSE_KEYWORDS,
  RELEVANCE_RULES,
  AUTO_APPROVABLE_SAFETY_LEVELS,
  SAFETY_MESSAGES,
  type UncertaintyPattern,
  type RelevanceRule,
} from "./safety.js";

// GitHub constants
export {
  GITHUB_CONTEXT_LIMITS,
  GITHUB_SIGNATURE,
  GITHUB_COMMENT_DISPLAY,
  FILE_PATH_VALIDATION,
  LOG_PARSING_LIMITS,
  EXCLUDED_PATH_PATTERNS,
  ERROR_INDICATORS,
  FILE_REFERENCE_PATTERNS,
  CI_FAILURE_DISPLAY,
  GITHUB_STATUS,
  GITHUB_CONCLUSION,
  GITHUB_ANNOTATION_LEVEL,
  GITHUB_ANNOTATION_LIMITS,
  TEXT_SANITIZATION_PATTERNS,
  SHORT_COMMIT_SHA_LENGTH,
} from "./github.js";

// OpenAI and text processing constants
export {
  OPENAI_DEFAULTS,
  OPENAI_CONSTANTS,
  EVIDENCE_TRUNCATION,
  MATCHING_CONFIG,
  SHA_PATTERN,
  SHA_PATTERN_SINGLE,
  QUOTED_TEXT_PATTERN,
  OPENAI_MESSAGES,
  TENANT_PROMPT_LIMITS,
  MODEL_VERSIONING,
  DATASET_THRESHOLDS,
  FINE_TUNING_CONFIG,
  FINE_TUNING_STATUS,
  FINE_TUNING_READINESS,
  FINE_TUNING_SCHEDULER,
  type FineTuningStatus,
} from "./openai.js";

// RAG constants
export {
  EMBEDDING_CONFIG,
  CHUNKING_CONFIG,
  VECTOR_SIMILARITY_THRESHOLDS,
  KNOWLEDGE_DOC_TYPES,
  RELATIONSHIP_TYPES,
  MULTI_HOP_CONFIG,
  RELATIONSHIP_DETECTION_CONFIG,
  EXTERNAL_SOURCE_TYPES,
  TECH_STACK_TAGS,
  EXTERNAL_SOURCE_CONFIG,
  TTL_POLICIES,
  DRIFT_DETECTION_THRESHOLDS,
  RAG_JOB_INTERVALS,
  RAG_EVALUATION_CONFIG,
  RAG_TEST_CASE_CONFIG,
  EMBEDDING_TIERS,
  COST_CONTROL_CONFIG,
  RAG_METRIC_TYPES,
  type KnowledgeDocType,
  type RelationshipType,
  type ExternalSourceType,
  type TechStackTag,
  type EmbeddingTierName,
  type RAGMetricType,
} from "./ragConstants.js";

// Secret detection constants
export {
  REDACTION_PLACEHOLDER,
  REDACTION_DEFAULTS,
  SECRET_PATTERNS,
  FORBIDDEN_FIELDS,
  type SecretPattern,
} from "./secrets.js";

// Slack-specific constants
export {
  SLACK_VERIFICATION,
  SLACK_API_LIMITS,
  SOCKET_MODE_ERROR_PATTERNS,
  isSocketModeDisconnectError,
} from "./slack.js";

// Database constants
export { DATABASE_POOL_DEFAULTS, QUERY_LOGGING, TRANSACTION_COMMANDS } from "./database.js";

// Action executor constants
export { ACTION_MESSAGES } from "./actions.js";

// Tenant constants
export {
  TENANT_STATUS,
  AUDIT_ACTIONS,
  AUDIT_DEFAULTS,
  TENANT_DEFAULTS,
  TENANT_QUERIES,
  AUDIT_QUERIES,
  TENANT_FIELD_MAP,
  AUDIT_FIELD_MAP,
} from "./tenant.js";

// Core module constants
export {
  LOGGER_DEFAULTS,
  CONFIG_DEFAULTS,
  VALID_NODE_ENVS,
  PARSE_INT_RADIX,
  HTTP_RESILIENCE_DEFAULTS,
  RETRYABLE_HTTP_STATUS_CODES,
  RETRYABLE_NETWORK_ERRORS,
  ID_GENERATION,
} from "./core.js";

// Redis constants
export {
  REDIS_STATUS,
  REDIS_RESPONSES,
  REDIS_LIST_OPS,
  REDIS_TTL_VALUES,
  REDIS_SCAN,
  REDIS_TIMEOUTS,
  REDIS_CONNECTION_DEFAULTS,
  RETRYABLE_ERROR_PATTERNS,
  SLACK_RETRYABLE_ERROR_PATTERNS,
  CACHE_TTL_SECONDS,
  REDIS_KEY_PREFIXES,
  CACHE_KEY_STRUCTURE,
  CACHE_NAMESPACES,
  QUEUE_WORKER_DEFAULTS,
  AGGREGATION_DEFAULTS,
  DISPLAY_DEFAULTS,
  RETRY_DEFAULTS,
  QUEUE_CONFIG,
  QUEUE_RETRY_CONFIG,
  QUEUE_VISIBILITY_TIMEOUT,
  QUEUE_NAMES,
  PUBSUB_CHANNELS,
  type CacheNamespace,
} from "./redis.js";

// API service constants
export {
  API_ROUTES,
  SWAGGER_ROUTES,
  RATE_LIMIT_SKIP_PATHS,
  HEALTH_STATUS,
  MEMORY_THRESHOLDS,
  API_RESPONSE_STATUS,
  API_MESSAGES,
  API_REDIS_PREFIXES,
  API_LOG_CONTEXT,
  API_LOG_LIMITS,
  API_REQUEST_FIELDS,
  shouldSkipRateLimit,
  type HealthStatus,
  type ApiResponseStatus,
} from "./api.js";

// Slack Bot service constants
export {
  SLACK_BOT_RATE_LIMITS,
  SLACK_BOT_TIMEOUTS,
  SLACK_BOT_DB_CONFIG,
  SLACK_MODAL_CALLBACKS,
  SLACK_ACTION_IDS,
  SLACK_ACTION_PATTERNS,
  SLACK_BLOCK_IDS,
  SLACK_OAUTH_TIMING,
  SLACK_OAUTH_SCOPES,
  SLACK_OAUTH_SCOPES_STRING,
  PRIORITY_NUMERIC_MAP,
  SLACK_BOT_MESSAGES,
  SLACK_BOT_HEALTH_PATH,
  shouldSkipSlackBotRateLimit,
  SLACK_CLIENT_CACHE,
  MESSAGE_STORE_CONFIG,
  RESOLUTION_SERVICE_CONFIG,
  ANALYSIS_CONTEXT_STORE_CONFIG,
  QA_CONFIG,
  QA_QUESTION_PATTERNS,
  QA_ACTION_IDS,
  QA_MESSAGES,
  isQuestionLike,
  DOC_INGESTION_CONFIG,
  DOC_INGESTION_PATTERNS,
  DOC_INGESTION_MESSAGES,
  isDocIngestionRequest,
  SLACK_UI_ERROR_MESSAGES,
  DOC_INGESTION_ERROR_CODES,
  type NumericPriority,
  type StringPriority,
} from "./slackBot.js";

// GitHub App service constants
export {
  GITHUB_APP_RATE_LIMITS,
  GITHUB_APP_HEALTH_PATHS,
  shouldSkipGitHubAppRateLimit,
  GITHUB_APP_TIMEOUTS,
  GITHUB_APP_DB_CONFIG,
  GITHUB_SETUP_CONFIG,
  GITHUB_APP_MESSAGES,
  KENCHI_BRANDING,
  GITHUB_COMMENT_TEMPLATES,
  SLACK_FAILURE_TEMPLATES,
  FORMATTER_DISPLAY_LIMITS,
  GITHUB_RETRY_CONFIG,
  GITHUB_PAGINATION,
  CONTEXT_FETCH_CONFIG,
} from "./githubApp.js";

// Passive learning constants
export {
  PASSIVE_LEARNING_TIME,
  FIX_COMMENT_PATTERNS,
  FIX_COMMENT_EXCLUSIONS,
  PR_FIX_COMMENT_CONFIG,
  SLACK_RESOLUTION_CONFIG,
  ANALYSIS_LESSON_CONFIG,
  KNOWLEDGE_QUALITY_WEIGHTS,
  SOURCE_RELIABILITY_SCORES,
  KNOWLEDGE_GC_CONFIG,
  FEEDBACK_URL_CONFIG,
} from "./passiveLearning.js";
