/**
 * Complete type definitions for the Kenchi DevOps Assistant.
 * Based on DATA_MODELS.md specifications.
 */

// ==================== Event Types ====================

export type EventType =
  | "CICD_FAILURE"
  | "DEPLOYMENT_FAILURE"
  | "MONITORING_ALERT"
  | "PERFORMANCE_DEGRADATION"
  | "ERROR_SPIKE"
  | "SECURITY_ALERT"
  | "MANUAL_TRIGGER"
  | "SERVICE_DOWN"
  | "TEST_FAILURE";

export type EventSeverity = "critical" | "high" | "medium" | "low" | "info";

export interface EventPayload {
  // CI/CD fields
  repository?: string;
  workflow?: string;
  runId?: string;
  branch?: string;
  commit?: string;

  // Error fields
  errorMessage?: string;
  errorLog?: string;

  // Monitoring fields
  alertId?: string;
  metricName?: string;
  metricValue?: number;
  threshold?: number;

  // Common fields
  url?: string;

  // Allow additional fields - use unknown for type safety
  [key: string]: unknown;
}

export interface EventMetadata {
  environment?: "production" | "staging" | "development" | "test";
  service?: string;
  team?: string;
  tags?: string[];
  [key: string]: unknown;
}

export interface Event {
  // Core identification
  id: string; // Format: evt_<alphanumeric>
  type: EventType;
  source: string;
  timestamp: string; // ISO 8601
  severity?: EventSeverity;
  title?: string;

  // Event-specific data
  payload: EventPayload;

  // Additional context
  metadata?: EventMetadata;

  // Audit timestamps
  createdAt?: string;
  updatedAt?: string;
}

// ==================== Evidence Types ====================

export interface LogEntry {
  source?: string;
  timestamp?: string;
  level?: "DEBUG" | "INFO" | "WARN" | "ERROR" | "FATAL";
  message: string;
  stackTrace?: string;
  metadata?: Record<string, unknown>;
}

export interface TimeSeriesMetric {
  metricName: string;
  values: Array<{
    timestamp: string;
    value: number;
  }>;
  unit?: string;
}

export interface MetricsSummary {
  errorRate?: number;
  requestRate?: number;
  cpuUsage?: number;
  memoryUsage?: number;
  latencyP50?: number;
  latencyP95?: number;
  latencyP99?: number;
  // Custom metrics can have any value type
  [key: string]: unknown;
}

export interface Metrics {
  timeRange?: {
    start: string;
    end: string;
  };
  timeSeries?: TimeSeriesMetric[];
  summary?: MetricsSummary;
}

export interface GitCommit {
  sha: string;
  message: string;
  author: string;
  timestamp: string;
  filesChanged?: string[];
  additions?: number;
  deletions?: number;
  url?: string;
}

export interface SystemState {
  deploymentStatus?: {
    currentVersion?: string;
    previousVersion?: string;
    deployedAt?: string;
    deployedBy?: string;
  };
  serviceHealth?: Record<string, "healthy" | "degraded" | "down" | "unknown">;
  dependencies?: Array<{
    name: string;
    status: "up" | "down" | "degraded";
    responseTime?: number;
  }>;
}

export interface KnowledgeDocument {
  id: string;
  type: "runbook" | "past_incident" | "documentation" | "best_practice" | "playbook";
  title: string;
  excerpt?: string;
  similarity: number;
  url?: string;
  metadata?: {
    createdAt?: string;
    updatedAt?: string;
    tags?: string[];
  };
}

export interface RelatedEvent {
  eventId: string;
  type: string;
  timestamp: string;
  correlation: "before" | "after" | "concurrent";
}

export interface Evidence {
  eventId: string;
  logs?: LogEntry[];
  metrics?: Metrics;
  gitHistory?: GitCommit[];
  systemState?: SystemState;
  relatedDocs?: KnowledgeDocument[];
  relatedEvents?: RelatedEvent[];
  collectedAt: string;
  collectionDuration?: number;
}

// ==================== LLM Analysis Result Types ====================

export interface ImpactAssessment {
  scope?: "isolated" | "service" | "system" | "organization";
  affectedUsers?: "none" | "few" | "some" | "many" | "all";
  businessImpact?: "none" | "low" | "medium" | "high" | "critical";
  description?: string;
}

export interface LLMRecommendedAction {
  actionType: string;
  description: string;
  reasoning?: string;
  priority?: "immediate" | "high" | "medium" | "low";
}

export interface EvidenceReference {
  type: "log" | "metric" | "commit" | "document" | "related_incident";
  reference: string;
  relevance?: string;
}

/**
 * Code annotation generated by AI analysis.
 * Points to specific file locations where errors or issues were detected.
 */
export interface LLMCodeAnnotation {
  path: string;
  line: number;
  level: "failure" | "warning" | "notice";
  message: string;
  title?: string;
}

/**
 * Dependency change detected by AI from PR diff.
 * Matches any package manager format (npm, pip, cargo, go, etc.)
 */
export interface LLMDetectedDependencyChange {
  readonly name: string;
  readonly type: "added" | "removed" | "updated";
  readonly oldVersion?: string;
  readonly newVersion?: string;
  readonly ecosystem?: string; // npm, pip, cargo, go, maven, etc.
}

/**
 * Build config change detected by AI from PR diff.
 * Works with any build system (webpack, tsconfig, pyproject, Makefile, etc.)
 */
export interface LLMDetectedBuildConfigChange {
  readonly file: string;
  readonly changeType: "added" | "modified" | "deleted";
  readonly summary: string; // Brief description of what changed
}

export interface LLMAnalysisResult {
  eventId: string;
  summary: string;
  identifiedCause?: string;
  impactAssessment?: ImpactAssessment;
  confidence?: "very_low" | "low" | "medium" | "high" | "very_high";
  confidenceScore?: number;
  reasoning?: string;
  codeAnnotations?: LLMCodeAnnotation[];
  recommendedActions?: LLMRecommendedAction[];
  uncertainties?: string[];
  evidenceUsed?: EvidenceReference[];
  relatedIncidents?: string[];
  nextSteps?: string[];
  analyzedAt: string;
  llmModel?: string;
  processingTime?: number;

  // AI-extracted structured data (Phase 3 - Language Agnostic)
  /** Dependency changes detected from PR diff (any package manager format) */
  detectedDependencyChanges?: LLMDetectedDependencyChange[];
  /** Build config changes detected from PR diff (any build system) */
  detectedBuildConfigChanges?: LLMDetectedBuildConfigChange[];
}

// ==================== Action Proposal Types ====================

export type ActionType =
  | "rollback_deployment"
  | "restart_service"
  | "scale_service"
  | "add_environment_variable"
  | "update_configuration"
  | "rerun_pipeline"
  | "notify_team"
  | "run_diagnostic"
  | "update_documentation"
  | "create_ticket"
  | "post_comment"
  | "execute_runbook"
  | "manual_investigation";

export type ActionPriority = "immediate" | "high" | "medium" | "low";

export type SafetyLevel = "safe" | "low_risk" | "medium_risk" | "high_risk" | "dangerous";

export type ActionStatus =
  | "proposed"
  | "approved"
  | "rejected"
  | "executing"
  | "completed"
  | "failed"
  | "rolled_back";

export interface ExecutionDetails {
  api?: string;
  endpoint?: string;
  method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  parameters?: Record<string, unknown>;
  command?: string;
  script?: string;
}

export interface ExecutionResult {
  success: boolean;
  message?: string;
  output?: string;
  error?: string;
}

export interface ActionProposal {
  // Identification
  id: string; // Format: act_<alphanumeric>
  eventId: string;

  // Action specification
  actionType: ActionType;
  description: string;
  reasoning?: string;

  // Confidence & safety
  confidence: number; // 0.0 to 1.0
  priority?: ActionPriority;
  safetyLevel: SafetyLevel;
  requiresApproval: boolean;
  autoExecutable?: boolean;

  // Execution details
  executionDetails?: ExecutionDetails;
  expectedOutcome?: string;
  rollbackPlan?: string;
  estimatedDuration?: number;
  dependencies?: string[];

  // Lifecycle tracking
  status?: ActionStatus;
  approvedBy?: string;
  approvedAt?: string;
  executedAt?: string;
  completedAt?: string;
  executionResult?: ExecutionResult;
  createdAt?: string;
}

// ==================== Confidence Scoring Types ====================

export interface ConfidenceScoreBreakdown {
  baseScore: number;
  uncertaintyAdjustment: number;
  evidenceAlignment: number;
  completeness: number;
  knowledgeBaseValidation: number;
  consistency: number;
}

export interface ConfidenceScoreResult {
  finalScore: number;
  breakdown: ConfidenceScoreBreakdown;
  reasoning: string[];
  gatingDecision: "auto_approve" | "require_approval" | "block";
}

// ==================== Validation Types ====================

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

// ==================== Legacy Webhook Event Types ====================
// These types are kept for backward compatibility with existing services

export interface WebhookEvent {
  source: string;
  type: string;
  payload: Record<string, unknown>;
  timestamp?: string;
}

export interface CIFailureEvent {
  repository: string;
  branch: string;
  commit: string;
  failureLog: string;
  jobName?: string;
  timestamp: string;
}

export interface SlackMessageEvent {
  channel: string;
  user: string;
  text: string;
  timestamp: string;
  threadTs?: string;
}

export interface GitHubPREvent {
  action: string;
  repository: {
    full_name: string;
    owner: { login: string };
    name: string;
  };
  pull_request: {
    number: number;
    title: string;
    body?: string;
    head: { sha: string; ref: string };
    base: { ref: string };
  };
}

// ==================== Multi-Tenant Types ====================

/**
 * Tenant status in the multi-tenant lifecycle.
 * - pending_slack: GitHub installed, awaiting Slack connection
 * - pending_github: Slack installed, awaiting GitHub connection
 * - active: Both installed, ready to use
 * - suspended: Temporarily disabled
 * - deleted: Soft deleted
 */
export type TenantStatus = "pending_slack" | "pending_github" | "active" | "suspended" | "deleted";

/**
 * Tenant entity - represents a customer organization using Kenchi.
 * Links a GitHub organization to a Slack workspace.
 */
export interface Tenant {
  readonly id: string;
  readonly githubOrg: string;
  readonly githubInstallationId: number | null;
  readonly githubAppInstalledAt: Date | null;
  readonly slackWorkspaceId: string | null;
  readonly slackTeamName: string | null;
  readonly slackBotToken: string | null;
  readonly slackBotUserId: string | null;
  readonly slackAppInstalledAt: Date | null;
  readonly status: TenantStatus;
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

/**
 * Data required to create a tenant from GitHub App installation.
 */
export interface CreateTenantFromGitHub {
  readonly githubOrg: string;
  readonly githubInstallationId: number;
}

/**
 * Data required to link a Slack workspace to an existing tenant.
 */
export interface LinkSlackWorkspace {
  readonly tenantId: string;
  readonly slackWorkspaceId: string;
  readonly slackTeamName: string;
  readonly slackBotToken: string;
  readonly slackBotUserId?: string;
}

/**
 * Tenant audit log action types.
 */
export type TenantAuditAction =
  | "github_installed"
  | "github_uninstalled"
  | "slack_installed"
  | "slack_uninstalled"
  | "activated"
  | "suspended"
  | "deleted"
  | "ci_failure_processed"
  | "slack_message_sent"
  | "github_comment_posted";

/**
 * Tenant audit log entry.
 */
export interface TenantAuditEntry {
  readonly id: string;
  readonly tenantId: string;
  readonly action: TenantAuditAction;
  readonly actor: string | null;
  readonly metadata: Record<string, unknown>;
  readonly createdAt: Date;
}

// ==================== Repository Channel Mapping Types ====================

/**
 * Maps a GitHub repository to a Slack channel for CI notifications.
 */
export interface RepositoryChannelMapping {
  readonly id: string;
  readonly tenantId: string;
  readonly repository: string; // Full repo name: "owner/repo"
  readonly slackChannelId: string;
  readonly slackChannelName: string | null;
  readonly createdBy: string | null; // Slack user ID
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

/**
 * Data required to create a new repository-channel mapping.
 */
export interface CreateRepositoryChannelMapping {
  readonly tenantId: string;
  readonly repository: string;
  readonly slackChannelId: string;
  readonly slackChannelName?: string;
  readonly createdBy?: string;
}

/**
 * GitHub repository info from API.
 */
export interface GitHubRepository {
  readonly id: number;
  readonly fullName: string; // "owner/repo"
  readonly name: string;
  readonly owner: string;
  readonly private: boolean;
  readonly defaultBranch: string;
}
