/**
 * Consolidated Poster Service
 *
 * Handles posting consolidated CI failure analysis to GitHub and Slack.
 * Called by the FailureAggregator when aggregation is ready.
 *
 * Uses message queue for Slack notifications for reliable delivery.
 */

import {
  createLogger,
  config,
  isRedisHealthy,
  enqueueConsolidatedNotification,
  resilientPost,
  getErrorMessage,
  generateFeedbackUrl,
  KENCHI_BRANDING,
  SHORT_COMMIT_SHA_LENGTH,
  GITHUB_COMMENT_DISPLAY,
  UI_EMOJI,
  type AggregatedFailures,
  type ConsolidatedPostResult,
} from "@kenchi/shared";
import {
  postPRComment,
  createCheckRunWithAnnotations,
  type CheckAnnotation,
} from "../githubService.js";

const logger = createLogger("github-app");

// ==================== Types ====================

interface FeedbackLinks {
  readonly correctUrl: string;
  readonly incorrectUrl: string;
}

interface SlackBlock {
  readonly type: "header" | "section" | "divider" | "actions";
  readonly text?: { readonly type: "mrkdwn" | "plain_text"; readonly text: string };
  readonly fields?: ReadonlyArray<{ readonly type: "mrkdwn"; readonly text: string }>;
  readonly elements?: readonly SlackBlockElement[];
}

interface SlackBlockElement {
  readonly type: "button";
  readonly text: { readonly type: "plain_text"; readonly text: string };
  readonly url?: string;
  readonly action_id?: string;
  readonly value?: string;
}

interface SlackPayload {
  readonly text: string;
  readonly blocks: readonly SlackBlock[];
}

// ==================== Simplified Formatters ====================

/**
 * Create feedback links for the comment.
 */
const createFeedbackLinks = async (analysisId: string): Promise<FeedbackLinks | null> => {
  const webhookSecret = config.GITHUB_WEBHOOK_SECRET;
  if (!webhookSecret) {
    return null;
  }

  try {
    const baseUrl = `${config.GITHUB_APP_URL}/api/feedback`;
    const [correctUrl, incorrectUrl] = await Promise.all([
      generateFeedbackUrl(baseUrl, analysisId, "correct", webhookSecret),
      generateFeedbackUrl(baseUrl, analysisId, "incorrect", webhookSecret),
    ]);
    return { correctUrl, incorrectUrl };
  } catch {
    return null;
  }
};

/**
 * Build consolidated PR comment from aggregated failures.
 */
const buildConsolidatedPRComment = (
  aggregation: AggregatedFailures,
  feedbackLinks?: FeedbackLinks
): string => {
  const shortSha = aggregation.commitSha.substring(0, SHORT_COMMIT_SHA_LENGTH);
  const failureCount = aggregation.failures.length;

  const lines: string[] = [
    `## ${UI_EMOJI.failure} CI Failure Analysis`,
    "",
    `| ${UI_EMOJI.info} **Commit** | ${UI_EMOJI.warning} **Failed Checks** |`,
    "| :--- | :--- |",
    `| \`${shortSha}\` | ${failureCount} |`,
    "",
  ];

  // Add summary of each failure
  aggregation.failures.forEach((failure) => {
    const cause = failure.identifiedCause ?? failure.analysis ?? "Unknown error";
    lines.push(`### ${UI_EMOJI.failure} ${failure.checkName}`);
    lines.push("");
    lines.push(`> ${cause}`);
    lines.push("");

    // Add recommended actions if any
    if (failure.recommendedActions?.length) {
      const actions = failure.recommendedActions.slice(0, GITHUB_COMMENT_DISPLAY.MAX_ACTIONS);
      lines.push(`**${UI_EMOJI.tools} Actions:**`);
      actions.forEach((action) => {
        lines.push(`- ${action.description}`);
      });
      lines.push("");
    }
  });

  // Add feedback links
  if (feedbackLinks) {
    lines.push("---");
    lines.push(
      `**Was this helpful?** [${UI_EMOJI.thumbsUp} Yes](${feedbackLinks.correctUrl}) | [${UI_EMOJI.thumbsDown} No](${feedbackLinks.incorrectUrl})`
    );
    lines.push("");
  }

  lines.push("---");
  lines.push(`${UI_EMOJI.robot} *Generated by KenchiOps DevOps Assistant*`);

  return lines.join("\n");
};

/**
 * Build consolidated Slack payload from aggregated failures.
 */
const buildConsolidatedSlackPayload = (aggregation: AggregatedFailures): SlackPayload => {
  const shortSha = aggregation.commitSha.substring(0, SHORT_COMMIT_SHA_LENGTH);
  const failureCount = aggregation.failures.length;
  const repository = aggregation.repository.fullName;
  // Build analysisId for feedback tracking (format: repository:commitSha)
  const analysisId = `${repository}:${aggregation.commitSha}`;

  const blocks: SlackBlock[] = [
    {
      type: "header",
      text: { type: "plain_text", text: `${UI_EMOJI.failure} CI Failure: ${repository}` },
    },
    {
      type: "section",
      fields: [
        { type: "mrkdwn", text: `*${UI_EMOJI.info} Commit:* \`${shortSha}\`` },
        { type: "mrkdwn", text: `*${UI_EMOJI.warning} Failed Checks:* ${failureCount}` },
      ],
    },
    { type: "divider" },
  ];

  // Add each failure as a section with recommended actions
  aggregation.failures.forEach((failure) => {
    const cause = failure.identifiedCause ?? failure.analysis ?? "Unknown error";

    // Build failure text with actions if available
    const actionsText =
      failure.recommendedActions && failure.recommendedActions.length > 0
        ? `\n\n*${UI_EMOJI.tools} Actions:*\n${failure.recommendedActions
            .slice(0, GITHUB_COMMENT_DISPLAY.MAX_ACTIONS)
            .map((action) => `  • ${action.description}`)
            .join("\n")}`
        : "";

    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*${UI_EMOJI.failure} ${failure.checkName}*\n>${cause}${actionsText}`,
      },
    });
  });

  blocks.push({ type: "divider" });

  // Add action buttons
  const prNumber = aggregation.pullRequestNumbers[0];
  const elements: SlackBlockElement[] = [];

  if (prNumber) {
    elements.push({
      type: "button",
      text: { type: "plain_text", text: "View PR" },
      url: `https://github.com/${repository}/pull/${prNumber}`,
    });
  }

  elements.push({
    type: "button",
    text: { type: "plain_text", text: "View Commit" },
    url: `https://github.com/${repository}/commit/${aggregation.commitSha}`,
  });

  blocks.push({ type: "actions", elements });

  // Add feedback section
  blocks.push({
    type: "section",
    text: { type: "mrkdwn", text: "*Was this helpful?*" },
  });

  const feedbackElements: SlackBlockElement[] = [
    {
      type: "button",
      text: { type: "plain_text", text: `${UI_EMOJI.thumbsUp} Yes` },
      action_id: "feedback_helpful",
      value: analysisId,
    },
    {
      type: "button",
      text: { type: "plain_text", text: `${UI_EMOJI.thumbsDown} No` },
      action_id: "feedback_not_helpful",
      value: analysisId,
    },
  ];

  blocks.push({ type: "actions", elements: feedbackElements });

  const failureCause = aggregation.failures[0]?.identifiedCause ?? "Unknown error";
  return {
    text: `CI Failure: ${repository} - ${failureCause}`,
    blocks,
  };
};

/**
 * Build check annotations from aggregated failures.
 */
const buildConsolidatedCheckAnnotations = (aggregation: AggregatedFailures): CheckAnnotation[] => {
  const annotations: CheckAnnotation[] = [];

  aggregation.failures.forEach((failure) => {
    failure.annotations?.forEach((annotation) => {
      if (annotation.path && annotation.line) {
        annotations.push({
          path: annotation.path,
          start_line: annotation.line,
          end_line: annotation.line,
          annotation_level:
            annotation.level === "failure"
              ? "failure"
              : annotation.level === "warning"
                ? "warning"
                : "notice",
          message: annotation.message,
          title: annotation.title,
        });
      }
    });
  });

  return annotations;
};

/**
 * Build check summary from aggregated failures.
 */
const buildConsolidatedCheckSummary = (aggregation: AggregatedFailures): string => {
  const failureCount = aggregation.failures.length;
  const causes = aggregation.failures
    .map((failure) => failure.identifiedCause ?? failure.analysis)
    .filter((cause): cause is string => Boolean(cause))
    .slice(0, GITHUB_COMMENT_DISPLAY.MAX_ACTIONS);

  const lines = [
    `Analyzed ${failureCount} failed check(s).`,
    "",
    "**Root Causes:**",
    ...causes.map((cause) => `- ${cause}`),
  ];

  return lines.join("\n");
};

/**
 * Check if Redis is available, with error handling.
 */
const checkRedisAvailability = async (): Promise<boolean> => {
  try {
    return await isRedisHealthy();
  } catch {
    return false;
  }
};

// ==================== Posting Functions ====================

/**
 * Post consolidated analysis to a single PR
 * Deletes old KenchiOps comments first to keep PR clean
 */
const postToPR = async (
  installationId: number,
  owner: string,
  repo: string,
  prNumber: number,
  commentBody: string
): Promise<boolean> => {
  try {
    // Delete old comments and post new one (deleteOldComments = true)
    await postPRComment(installationId, owner, repo, prNumber, commentBody, true);
    return true;
  } catch (error) {
    logger.error("Failed to post consolidated comment to PR", {
      prNumber,
      error: getErrorMessage(error),
    });
    return false;
  }
};

/**
 * Post PR comments and return count of successful posts.
 */
const postPRComments = async (
  installationId: number,
  owner: string,
  repo: string,
  pullRequestNumbers: readonly number[],
  commentBody: string
): Promise<{ successCount: number; errors: string[] }> => {
  if (pullRequestNumbers.length === 0) {
    return { successCount: 0, errors: [] };
  }

  const results = await Promise.all(
    pullRequestNumbers.map((prNumber) =>
      postToPR(installationId, owner, repo, prNumber, commentBody)
    )
  );

  const successCount = results.filter(Boolean).length;
  const failCount = pullRequestNumbers.length - successCount;
  const errors = failCount > 0 ? [`Failed to post to ${failCount} PR(s)`] : [];

  return { successCount, errors };
};

/**
 * Create check run with annotations.
 * Returns success status and any errors.
 */
const createCheckAnnotations = async (
  aggregation: AggregatedFailures,
  annotations: CheckAnnotation[]
): Promise<{ created: boolean; errors: string[] }> => {
  if (annotations.length === 0) {
    return { created: false, errors: [] };
  }

  const { repository, installationId, commitSha } = aggregation;

  try {
    const summary = buildConsolidatedCheckSummary(aggregation);

    await createCheckRunWithAnnotations({
      installationId,
      owner: repository.owner,
      repo: repository.name,
      headSha: commitSha,
      name: KENCHI_BRANDING.CHECK_RUN_NAME,
      summary,
      annotations,
    });

    logger.info("Created consolidated check run with annotations", {
      repository: repository.fullName,
      annotationCount: annotations.length,
      failureCount: aggregation.failures.length,
    });

    return { created: true, errors: [] };
  } catch (error) {
    const errorMsg = getErrorMessage(error);
    logger.error("Failed to create consolidated check annotations", { error: errorMsg });
    return { created: false, errors: [`Failed to create check annotations: ${errorMsg}`] };
  }
};

/**
 * Post consolidated analysis to GitHub (PR comments and check annotations).
 * Uses functional composition - no let declarations.
 */
const postToGitHub = async (
  aggregation: AggregatedFailures
): Promise<{ prCommentsPosted: number; checkAnnotationsCreated: boolean; errors: string[] }> => {
  const { repository, installationId, pullRequestNumbers } = aggregation;
  const analysisId = `${repository.fullName}:${aggregation.commitSha}`;
  const feedbackLinks = await createFeedbackLinks(analysisId);

  // Build consolidated PR comment
  const commentBody = buildConsolidatedPRComment(aggregation, feedbackLinks ?? undefined);

  // Post PR comments
  const prResult = await postPRComments(
    installationId,
    repository.owner,
    repository.name,
    pullRequestNumbers,
    commentBody
  );

  if (prResult.successCount > 0) {
    logger.info("Posted consolidated PR comments", {
      repository: repository.fullName,
      totalPRs: pullRequestNumbers.length,
      successfulPosts: prResult.successCount,
    });
  }

  // Create check annotations
  const annotations = buildConsolidatedCheckAnnotations(aggregation);
  const annotationResult = await createCheckAnnotations(aggregation, annotations);

  return {
    prCommentsPosted: prResult.successCount,
    checkAnnotationsCreated: annotationResult.created,
    errors: [...prResult.errors, ...annotationResult.errors],
  };
};

/**
 * Post consolidated analysis to Slack via message queue.
 * Falls back to direct HTTP if Redis is unavailable.
 */
const postToSlack = async (
  aggregation: AggregatedFailures
): Promise<{ success: boolean; error?: string }> => {
  const slackPayload = buildConsolidatedSlackPayload(aggregation);

  // Check if Redis is available for queue-based delivery
  const redisAvailable = await checkRedisAvailability();

  if (redisAvailable) {
    // Queue-based delivery (preferred - reliable with retries)
    try {
      const messageId = await enqueueConsolidatedNotification(aggregation, slackPayload);

      logger.info("Enqueued consolidated Slack notification", {
        messageId,
        repository: aggregation.repository.fullName,
        failureCount: aggregation.failures.length,
      });

      return { success: true };
    } catch (error) {
      const errorMsg = getErrorMessage(error);
      logger.warn("Failed to enqueue Slack notification, falling back to direct HTTP", {
        error: errorMsg,
      });
      // Fall through to direct HTTP
    }
  }

  // Direct HTTP fallback (when Redis unavailable)
  const slackUrl = `${config.SLACK_BOT_URL}/slack/message`;

  try {
    const response = await resilientPost<{ success: boolean }>(slackUrl, {
      consolidated: true,
      payload: slackPayload,
      repository: aggregation.repository.fullName,
      installation_id: aggregation.installationId,
      commit_sha: aggregation.commitSha,
      failure_count: aggregation.failures.length,
    });

    logger.info("Posted consolidated Slack message (direct HTTP)", {
      repository: aggregation.repository.fullName,
      failureCount: aggregation.failures.length,
      retryCount: response.retryCount,
      duration: response.duration,
    });

    return { success: true };
  } catch (error) {
    const errorMsg = getErrorMessage(error);
    logger.error("Failed to post consolidated Slack message", {
      error: errorMsg,
    });
    return { success: false, error: errorMsg };
  }
};

/**
 * Post consolidated analysis to all channels (GitHub + Slack)
 *
 * This is the main callback for the FailureAggregator.
 */
export const postConsolidatedAnalysis = async (
  aggregation: AggregatedFailures
): Promise<ConsolidatedPostResult> => {
  const errors: string[] = [];

  logger.info("Posting consolidated analysis", {
    repository: aggregation.repository.fullName,
    commitSha: aggregation.commitSha.substring(0, SHORT_COMMIT_SHA_LENGTH),
    failureCount: aggregation.failures.length,
    checkNames: aggregation.failures.map((failure) => failure.checkName),
    prCount: aggregation.pullRequestNumbers.length,
  });

  // Post to GitHub and Slack in parallel
  const [githubResult, slackResult] = await Promise.all([
    postToGitHub(aggregation),
    postToSlack(aggregation),
  ]);

  // Collect errors
  errors.push(...githubResult.errors);
  if (slackResult.error) {
    errors.push(slackResult.error);
  }

  const success =
    (githubResult.prCommentsPosted > 0 || aggregation.pullRequestNumbers.length === 0) &&
    slackResult.success;

  return {
    success,
    prCommentsPosted: githubResult.prCommentsPosted,
    slackMessageSent: slackResult.success,
    checkAnnotationsCreated: githubResult.checkAnnotationsCreated,
    errors,
  };
};
