/**
 * PR Comment Formatter
 *
 * Formats aggregated CI failures into GitHub PR comments.
 * Produces clean, organized markdown output with failure details
 * and recommended actions.
 */

import type {
  AggregatedFailures,
  AnalyzedFailure,
  CodeAnnotation,
  RecommendedAction,
} from "@kenchi/shared";
import {
  DISPLAY_LIMITS,
  getPriorityEmoji,
  calculateAverageConfidence,
  mergeRecommendedActions,
} from "./formatterUtils.js";

// ==================== Constants ====================

/**
 * Level icons for annotations
 */
const LEVEL_ICONS: Readonly<Record<CodeAnnotation["level"], string>> = {
  failure: "❌",
  warning: "⚠️",
  notice: "ℹ️",
} as const;

// ==================== Helper Functions ====================

/**
 * Format a single annotation as markdown
 */
const formatAnnotation = (annotation: CodeAnnotation): string => {
  const icon = LEVEL_ICONS[annotation.level];
  const title = annotation.title ? `**${annotation.title}**: ` : "";
  return `  - ${icon} \`${annotation.path}:${annotation.line}\` - ${title}${annotation.message}`;
};

/**
 * Format a recommended action as markdown
 */
const formatAction = (action: RecommendedAction, index: number): string => {
  const emoji = getPriorityEmoji(action.priority);
  return `${index + 1}. ${emoji} ${action.description}`;
};

/**
 * Format a single failure section for PR comment
 */
const formatFailureSection = (failure: AnalyzedFailure, showAnnotations: boolean): string[] => {
  const lines: string[] = [
    `### ❌ ${failure.checkName}`,
    "",
    `**Root Cause:** ${failure.identifiedCause ?? failure.analysis ?? "Unable to determine"}`,
    `**Confidence:** ${Math.round(failure.confidence * 100)}%`,
    "",
  ];

  if (showAnnotations && failure.annotations.length > 0) {
    lines.push("**Affected Files:**");
    const displayAnnotations = failure.annotations.slice(0, DISPLAY_LIMITS.annotationsPerCheck);
    lines.push(...displayAnnotations.map(formatAnnotation));

    if (failure.annotations.length > DISPLAY_LIMITS.annotationsPerCheck) {
      lines.push(
        `  - ... and ${failure.annotations.length - DISPLAY_LIMITS.annotationsPerCheck} more locations`
      );
    }
    lines.push("");
  }

  return lines;
};

// ==================== Public API ====================

/**
 * Build consolidated PR comment body from aggregated failures.
 * Creates a comprehensive markdown summary with all failure details.
 */
export const buildConsolidatedPRComment = (aggregation: AggregatedFailures): string => {
  const { failures, commitSha, prContext } = aggregation;
  const avgConfidence = calculateAverageConfidence(failures);
  const mergedActions = mergeRecommendedActions(failures);

  // Header
  const lines: string[] = [
    "## 🤖 KenchiOps CI Failure Analysis",
    "",
    `**Commit:** \`${commitSha.substring(0, 7)}\``,
    `**Failed Checks:** ${failures.length}`,
    `**Overall Confidence:** ${Math.round(avgConfidence * 100)}%`,
  ];

  // PR context if available
  if (prContext) {
    lines.push(`**Branch:** \`${prContext.branch}\` → \`${prContext.baseBranch}\``);
  }

  lines.push("", "---", "");

  // Individual failure sections
  const failuresToShow = failures.slice(0, DISPLAY_LIMITS.checksToShow);
  const totalAnnotations = failures.reduce((sum, f) => sum + f.annotations.length, 0);
  const showAnnotations = totalAnnotations <= DISPLAY_LIMITS.totalAnnotations;

  const failureSections = failuresToShow.flatMap((failure) =>
    formatFailureSection(failure, showAnnotations)
  );
  lines.push(...failureSections);

  if (failures.length > DISPLAY_LIMITS.checksToShow) {
    lines.push(`*... and ${failures.length - DISPLAY_LIMITS.checksToShow} more failed checks*`, "");
  }

  // Consolidated recommended actions
  if (mergedActions.length > 0) {
    lines.push("---", "", "## 🛠️ Recommended Actions", "");
    lines.push(...mergedActions.map(formatAction));
    lines.push("");
  }

  // Footer
  lines.push("---", "*Generated by KenchiOps DevOps Assistant*");

  return lines.join("\n");
};
