/**
 * PR Comment Formatter
 *
 * Formats aggregated CI failures into GitHub PR comments.
 * Produces clean, organized markdown output with consolidated failure details
 * and recommended actions.
 *
 * Section builders are in prCommentSections.ts.
 * Types are in prCommentTypes.ts.
 * Helper functions are in prCommentHelpers.ts.
 */

import {
  canonicalizeEvidencePaths,
  extractServiceFromPath,
  countUniqueSuites,
  selectMessageVariant,
  clusterFailuresByService,
  type AggregatedFailures,
} from "@kenchi/shared";
import {
  calculateConfidenceWithUncertainty,
  mergeRecommendedActions,
  type FeedbackLinks,
} from "./formatterUtils.js";
import {
  countDisplayableFiles,
  consolidateTestFailures,
  consolidateAnnotations,
} from "./prCommentHelpers.js";
import {
  buildHeader,
  buildCheckNamesSection,
  buildInfrastructureIssuesSection,
  buildFlakyWarningSection,
  buildAtAGlanceSection,
  buildClusteredRootCauseSection,
  buildAnnotationsSection,
  buildActionsSection,
  buildFeedbackSection,
  buildPRContextCorrelationSection,
  buildFullReportLinkSection,
} from "./prCommentSections.js";

// Re-export types for external consumers
export type {
  ConsolidatedTestFailure,
  ConsolidatedAnnotation,
  HeaderConfig,
} from "./prCommentTypes.js";

// ==================== Public API ====================

/**
 * Build consolidated PR comment body from aggregated failures.
 * Creates a comprehensive markdown summary with deduplicated failure details.
 * Includes clustered root causes, evidence IDs, and multi-module uncertainty detection.
 *
 * @param aggregation - Aggregated failures for the commit
 * @param feedbackLinks - Optional feedback URLs for user rating
 * @returns Formatted markdown string for the PR comment
 */
export const buildConsolidatedPRComment = (
  aggregation: AggregatedFailures,
  feedbackLinks?: FeedbackLinks
): string => {
  const { failures, commitSha, prContext, repository } = aggregation;

  // Phase 5: Select message variant based on failure complexity
  const variantResult = selectMessageVariant(
    failures.map((failure) => {
      const firstTestPath = failure.testFailures?.[0]?.file;
      const service = firstTestPath ? extractServiceFromPath(firstTestPath) : undefined;
      return { checkName: failure.checkName, service };
    })
  );

  // Calculate confidence with multi-module uncertainty detection
  const { confidence, uncertainty } = calculateConfidenceWithUncertainty(failures);
  const mergedActions = mergeRecommendedActions(failures);

  // Pre-compute consolidated data (O(n) with Map-based deduplication)
  const rawTestFailures = failures.flatMap((failure) => failure.testFailures ?? []);
  const rawAnnotations = failures.flatMap((failure) => failure.annotations ?? []);
  const { testFailures: canonicalTestFailures, annotations: canonicalAnnotations } =
    canonicalizeEvidencePaths(rawTestFailures, rawAnnotations);
  const testFailures = consolidateTestFailures(canonicalTestFailures);
  const annotations = consolidateAnnotations(canonicalAnnotations);

  // Calculate suite, file, and service counts
  const suiteCount = countUniqueSuites(testFailures);
  const fileCount = countDisplayableFiles(annotations, testFailures);
  const serviceClusters = clusterFailuresByService(failures);
  const serviceCount = serviceClusters.size;

  // Extract failing test file paths for PR context correlation
  const failingTestFiles = testFailures
    .map((failure) => failure.file)
    .filter((file): file is string => Boolean(file));

  // Build all sections (test failures consolidated into Affected Files)
  const lines: string[] = [
    ...buildHeader({
      commitSha,
      failureCount: failures.length,
      confidence,
      uncertainty,
      suiteCount,
      fileCount,
      serviceCount,
      prContext,
    }),
    "",
    "---",
    ...buildCheckNamesSection(failures),
    ...buildInfrastructureIssuesSection(testFailures),
    ...buildFlakyWarningSection(testFailures),
    ...buildPRContextCorrelationSection(prContext, failingTestFiles),
    ...buildAtAGlanceSection(failures, variantResult.variant),
    ...buildClusteredRootCauseSection(failures),
    ...buildAnnotationsSection(annotations, testFailures),
    ...buildActionsSection(mergedActions),
    ...buildFullReportLinkSection(repository, commitSha, variantResult.showFullReportLink),
    ...buildFeedbackSection(feedbackLinks),
    "---",
    "*Generated by KenchiOps DevOps Assistant*",
  ];

  return lines.join("\n");
};
