/* eslint-disable max-lines */
/**
 * Kenchi Shared Package
 *
 * This package provides all shared functionality used across services.
 * Import everything from this package using: import { ... } from "@kenchi/shared";
 */

// Core infrastructure
export { config, type Config } from "./core/index.js";
export { createLogger, logger, LogLevel, type Logger } from "./core/index.js";
export {
  withTimeout,
  isRetryableError,
  delay,
  safeJsonParse,
  parseDbCount,
  generateEventId,
  generateUrlSignature,
  verifyUrlSignature,
  generateFeedbackUrl,
  parseFeedbackUrl,
  type SignedUrlParams,
} from "./core/index.js";
export {
  AppError,
  ValidationError,
  AuthenticationError,
  AuthorizationError,
  NotFoundError,
  ExternalServiceError,
  LLMError,
  RateLimitError,
  CircuitBreakerOpenError,
  isAppError,
  isRetryableAppError,
  isExternalServiceError,
  getErrorMessage,
  getUserFriendlyMessage,
  getRetryInfo,
  formatErrorForLog,
  wrapError,
  enrichError,
  type ErrorContext,
} from "./core/index.js";
export type {
  // Event Types
  Event,
  EventType,
  EventSeverity,
  EventPayload,
  EventMetadata,
  // Evidence Types
  Evidence,
  LogEntry,
  TimeSeriesMetric,
  MetricsSummary,
  Metrics,
  GitCommit,
  SystemState,
  KnowledgeDocument,
  RelatedEvent,
  // LLM Analysis Types
  LLMAnalysisResult,
  LLMCodeAnnotation,
  LLMSuggestedFix,
  ImpactAssessment,
  LLMRecommendedAction,
  EvidenceReference,
  LLMDetectedDependencyChange,
  LLMDetectedBuildConfigChange,
  // Failure Classification Types
  FailureCategory,
  PipelinePhase,
  // Action Proposal Types
  ActionProposal,
  ActionType,
  ActionPriority,
  SafetyLevel,
  ActionStatus,
  ExecutionDetails,
  ExecutionResult,
  // Confidence Scoring Types
  ConfidenceScoreBreakdown,
  ConfidenceScoreResult,
  // Validation Types
  ValidationResult,
  // Multi-Tenant Types
  Tenant,
  TenantStatus,
  CreateTenantFromGitHub,
  LinkSlackWorkspace,
  TenantAuditAction,
  TenantAuditEntry,
  // Repository Channel Mapping Types
  RepositoryChannelMapping,
  CreateRepositoryChannelMapping,
  GitHubRepository,
  // Legacy Types (backward compatibility)
  WebhookEvent,
  CIFailureEvent,
  SlackMessageEvent,
  GitHubPREvent,
} from "./core/index.js";

// Database access
export {
  initDatabase,
  getPool,
  query,
  transaction,
  closeDatabase,
  isDatabaseHealthy,
  type QueryResult,
} from "./database/index.js";
export {
  findByGitHubInstallation,
  findByGitHubOrg,
  findBySlackWorkspace,
  findById,
  getActiveTenants,
  createFromGitHubInstall,
  linkSlackWorkspace,
  createFromSlackInstall,
  activate,
  suspend,
  deleteTenant,
  handleGitHubUninstall,
  logAuditEvent,
  getAuditLog,
  updateSlackToken,
  getSlackCredentials,
  getTenantStatistics,
  type TenantStatistics,
} from "./database/index.js";
export {
  findChannelForRepository,
  findMappingsForChannel,
  findAllMappingsForTenant,
  getMappedRepositories,
  createMapping,
  deleteMapping,
  deleteMappingsForChannel,
  isMapped,
} from "./database/index.js";
export {
  // Vector types
  type DiffChunk,
  type CreateDiffChunkInput,
  type KnowledgeDocRecord,
  type CreateKnowledgeDocInput,
  type VectorSearchResult,
  type VectorSearchFilters,
  // Diff chunk repository
  createDiffChunk,
  createDiffChunksBatch,
  searchSimilarDiffChunks,
  getDiffChunksWithoutEmbeddings,
  updateDiffChunkEmbedding,
  deleteDiffChunksByPR,
  deleteDiffChunksByTenant,
  getDiffChunkCount,
  // Knowledge document repository
  createKnowledgeDoc,
  createKnowledgeDocsBatch,
  searchSimilarKnowledgeDocs,
  getKnowledgeDocsWithoutEmbeddings,
  updateKnowledgeDocEmbedding,
  deleteKnowledgeDocsByParent,
  deleteKnowledgeDocsByTenant,
  getDocsNeedingReembedding,
  getKnowledgeDocsByType,
  getKnowledgeDocCountsByType,
} from "./database/index.js";
export {
  // Feedback repository
  createRAGFeedback,
  createAnalysisFeedback,
  getFeedbackByAnalysis,
  getRAGFeedbackMetrics,
  getRAGFeedbackByDoc,
  createOrUpdateAnalysisFeedback,
  createQAFeedback,
  createOrUpdateQAFeedback,
  getQAFeedbackByQueryAndUser,
  type FeedbackType,
  type CreateRAGFeedbackInput,
  type CreateAnalysisFeedbackInput,
  type CreateQAFeedbackInput,
  type FeedbackRecord,
  type RAGFeedbackMetrics,
  // Action proposal repository
  updateActionProposalStatus,
  getActionProposalById,
  getActionProposalsByAnalysis,
  getActionApprovalStats,
  type ActionProposalStatus,
  type UpdateActionStatusInput,
  type ActionProposalRecord,
  type ActionApprovalStats,
} from "./database/index.js";
export {
  createModelVersion,
  getModelVersionById,
  getAllModelVersionsFromDB,
  getBaselineModelFromDB,
  deleteModelVersion,
  saveFeatureFlags,
  getFeatureFlagsFromDB,
  setRollbackActive,
  updateTenantOverrides,
  type CreateModelVersionInput,
  type SaveFeatureFlagsInput,
} from "./database/index.js";
export {
  createAnalysis,
  getAnalysisById,
  getAnalysisByEventId,
  getAnalysesByModelVersion,
  countAnalysesByModelVersion,
  type CreateAnalysisInput,
  type AnalysisRecord,
} from "./database/index.js";

// HTTP utilities
export { errorHandler, asyncHandler, requestLogger } from "./http/index.js";
export { validate, validators, type ValidationSchema } from "./http/index.js";
export {
  createRateLimiter,
  defaultRateLimiter,
  createRedisRateLimiter,
  defaultRedisRateLimiter,
  type RateLimitOptions,
  type RateLimitInfo,
} from "./http/index.js";
export {
  resilientFetch,
  resilientGet,
  resilientPost,
  resilientPut,
  resilientPatch,
  resilientDelete,
  resetCircuitBreaker,
  getCircuitBreakerStatus,
  type ResilientRequestOptions,
  type ResilientResponse,
} from "./http/index.js";
export {
  withCircuitBreaker,
  getCircuitStatus,
  resetCircuit,
  resetAllCircuits,
  getAllCircuitStatus,
  SERVICE_KEYS,
  type CircuitBreakerConfig,
  type CircuitBreakerStatus,
} from "./http/index.js";

// Formatting utilities
export {
  getConfidenceLabel,
  getConfidenceLabelParenthesized,
  getConfidenceColor,
  getConfidenceEmoji,
  truncateText,
  sanitizeIdPart,
  formatRelativeTime,
  pluralize,
  getRepoName,
  getFirstSentence,
  buildTruncatedList,
} from "./formatting/index.js";
export {
  deduplicateByKey,
  containsAny,
  startsWithAny,
  shouldExcludePath,
  groupBy,
  takeMatching,
} from "./formatting/index.js";
export {
  collectCIErrors,
  formatDependencyChange,
  formatDependencyChanges,
  normalizeTestFailure,
  type CIAnnotation,
  type CITestFailure,
  type CollectErrorsOptions,
  type DependencyChange,
  type DependencyChangeType,
} from "./formatting/index.js";

// Integrations
export { fetchInstallationRepositories } from "./integrations/index.js";
export { VectorStore, InMemoryVectorStore } from "./integrations/index.js";
export {
  buildSystemPrompt,
  buildAnalysisPrompt,
  formatEvent,
  formatEvidence,
  formatLogs,
  formatMetrics,
  formatGitHistory,
  formatRelatedEvents,
  formatKnowledgeDocs,
  estimateTokens,
  truncateEvidence,
} from "./integrations/index.js";
export {
  buildTenantPromptAdditions,
  createTenantPromptConfig,
  validateTenantPromptConfig,
  type TenantPromptConfig,
  type TechStackConfig,
  type CISystem,
  type AnalysisDepth,
  type PromptPreferences,
  type FocusArea,
  type VerbosityLevel,
} from "./integrations/index.js";

// OpenAI client
export { OpenAIClient } from "./openaiClient/index.js";
export {
  splitEvidenceSections,
  type EvidenceSectionBlock,
  isGenericErrorLine,
} from "./openaiClient/index.js";
export {
  EmbeddingClient,
  getEmbeddingClient,
  clearClientCache,
  createEmbeddingProvider,
  type EmbeddingResult,
  type BatchEmbeddingResult,
  type EmbeddingProvider,
} from "./openaiClient/index.js";

// Safety and confidence scoring
export {
  calculateConfidenceScore,
  determineActionGating,
  confidenceScore,
  shouldActOnResult,
} from "./safety/index.js";

// Security utilities
export {
  redactSecrets,
  redactSecretsWithStats,
  redactObject,
  isForbiddenField,
  containsSecrets,
  detectSecretTypes,
  createCustomRedactor,
  type RedactionResult,
} from "./security/index.js";

// Action execution
export {
  executeAction,
  validateActionExecution,
  isActionExecutable,
  getExecutableActionTypes,
  enqueueAction,
  startActionQueueWorker,
  getActionQueueStats,
  storeActionPayload,
  retrieveActionPayload,
  deleteActionPayload,
  parseOpaqueActionValue,
  getActionStoreStats,
  clearActionStore,
  type ActionExecutionContext,
  type ActionExecutionResult,
  type ActionJobPayload,
  type ActionResultEvent,
  type StoredActionPayload,
  type OpaqueActionValue,
  type ActionVerificationContext,
} from "./actions/index.js";

// Constants (re-export all)
export * from "./constants/index.js";

// Redis queue and pub/sub
export {
  getRedisClient,
  getSubscriberClient,
  isRedisHealthy,
  waitForRedisConnection,
  closeRedis,
  publish,
  subscribe,
  createQueue,
  ciAnalysisQueue,
  slackNotificationQueue,
  githubActionQueue,
  CHANNELS,
  type RedisOptions,
  type QueueMessage,
  type ProcessResult,
  type MessageHandler,
  type SubscriptionHandler,
  type QueueConfig,
  // Slack notification queue
  enqueueConsolidatedNotification,
  enqueueActionResultNotification,
  enqueueSystemAlert,
  startSlackNotificationWorker,
  getSlackNotificationQueueStats,
  type SlackNotificationType,
  type ConsolidatedCIFailurePayload,
  type ActionResultPayload,
  type SystemAlertPayload,
  type SlackNotificationPayload,
  type NotificationHandler,
} from "./queue/index.js";

// Redis caching
export {
  // Core cache operations
  cacheGet,
  cacheSet,
  cacheDelete,
  cacheDeletePattern,
  cacheExists,
  cacheTTL,
  cacheGetOrSet,
  cacheGetMany,
  getCacheStats,
  resetCacheStats,
  CACHE_TTL,
  CACHE_NAMESPACE,
  // GitHub cache
  getCachedPullRequest,
  cachePullRequest,
  getOrFetchPullRequest,
  getCachedPullRequestDiff,
  cachePullRequestDiff,
  getOrFetchPullRequestDiff,
  // Tenant cache
  toCachedTenant,
  toCachedMapping,
  getCachedTenantById,
  cacheTenantById,
  getOrFetchTenantById,
  getCachedTenantByInstallation,
  cacheTenantByInstallation,
  getOrFetchTenantByInstallation,
  getCachedTenantBySlackWorkspace,
  cacheTenantBySlackWorkspace,
  getOrFetchTenantBySlackWorkspace,
  getCachedChannelForRepo,
  cacheChannelForRepo,
  getOrFetchChannelForRepo,
  getCachedAllMappingsForTenant,
  cacheAllMappingsForTenant,
  getOrFetchAllMappingsForTenant,
  invalidateTenantCache,
  invalidateMappingCache,
  invalidateRepositoryMapping,
  // Analysis cache
  generateLogHash,
  getCachedCheckAnalysis,
  cacheCheckAnalysis,
  getOrFetchCheckAnalysis,
  getCachedAnalysisByLogHash,
  cacheAnalysisByLogHash,
  getOrFetchAnalysisByLogHash,
  buildCachedAnalysis,
  invalidateRepositoryAnalysisCache,
  hasAnalysisInCache,
  hasLogHashInCache,
  // Cache key utilities
  githubCacheKeys,
  tenantCacheKeys,
  mappingCacheKeys,
  analysisCacheKeys,
  // Types
  type CacheEntry,
  type CacheResult,
  type CacheSetOptions,
  type CacheStats,
  type CachedPullRequest,
  type CachedTenant,
  type CachedMapping,
  type CachedTenantStats,
  type CachedAnalysis,
  type CachedAnnotation,
  type CachedAction,
} from "./cache/index.js";

// Redis-based aggregation
export {
  // Types
  type CodeAnnotation,
  type RecommendedAction,
  type TestFailureInfo,
  type RelatedKnowledgeDoc,
  type SuggestedFix,
  type AnalyzedFailure,
  type SerializedFailure,
  type PRContext,
  type WorkflowContext,
  type RepositoryInfo,
  type AggregatedFailures,
  type AggregationKey,
  type AggregationConfig,
  type ConsolidatedPostResult,
  type AggregationReadyCallback,
  type ConsolidatedAnalysisPayload,
  type FailureContext,
  // Utilities
  serializeAggregationKey,
  deserializeAggregationKey,
  DEFAULT_AGGREGATION_CONFIG,
  AGGREGATION_KEYS,
  // Redis operations
  addFailureToRedis,
  getAggregationFromRedis,
  deleteAggregationFromRedis,
  isDebounceExpired,
  isMaxWaitExceeded,
  findReadyAggregations,
  enqueueAggregation,
  // Workers
  startAggregatorWorker,
  startAnalysisQueueProcessor,
  deserializeQueuePayload,
} from "./aggregation/index.js";

// Health check utilities
export {
  // Types (HealthStatus comes from constants for consistency)
  type ComponentHealth,
  type ServiceHealth,
  type MemoryHealth,
  type HealthCheckConfig,
  // Health check functions
  getMemoryHealth,
  checkMemoryStatus,
  checkDatabaseHealth,
  checkRedisHealth,
  checkCircuitBreakerHealth,
  checkAllCircuitBreakers,
  performHealthCheck,
  livenessCheck,
  readinessCheck,
} from "./health/index.js";

// Graceful shutdown utilities
export {
  setupGracefulShutdown,
  registerCleanupHandler,
  isShuttingDown,
  getShutdownStatus,
  type CleanupFunction,
  type GracefulShutdownConfig,
} from "./shutdown/index.js";

// RAG (Retrieval-Augmented Generation) utilities
export {
  chunkText,
  chunkDiff,
  chunkKnowledgeDoc,
  splitMarkdownSections,
  estimateTokenCount,
  type ChunkMetadata,
  type TextChunk,
  type ChunkingOptions,
  type DiffChunkResult,
  type KnowledgeChunkResult,
  type MarkdownSection,
  // Ingestion functions
  ingestDiffChunks,
  ingestKnowledgeDoc,
  processPendingEmbeddings,
  type IngestDiffInput,
  type IngestDiffResult,
  type IngestKnowledgeDocInput,
  type IngestKnowledgeDocResult,
  // Metrics functions
  recordEmbeddingOperation,
  recordIngestionOperation,
  getEmbeddingMetrics,
  getIngestionMetrics,
  getRAGMetricsSnapshot,
  logRAGMetrics,
  checkRAGAlerts,
  resetMetrics,
  type EmbeddingMetrics,
  type IngestionMetrics,
  type RAGMetricsSnapshot,
  // Search functions
  searchDiffChunks,
  searchKnowledgeDocs,
  searchAll,
  searchFromEventContext,
  clearEmbeddingCache,
  type SearchQuery,
  type DiffSearchQuery,
  type KnowledgeSearchQuery,
  type RAGSearchResult,
  type EventQueryContext,
  // Governance functions
  getTenantRAGStats,
  purgeTenantRAGData,
  purgePRDiffChunks,
  purgeKnowledgeDocChunks,
  triggerReembedding,
  checkRAGHealth,
  type RAGTenantStats,
  type PurgeResult,
  type ReembeddingResult,
  type ReembeddingConfig,
  type RAGHealthStatus,
  // Evaluation functions
  calculateRecallAtK,
  calculateMRR,
  calculateHelpfulRate,
  recordRAGFeedback,
  runRAGTestCase,
  getRAGEvaluationMetrics,
  type RAGRelevance,
  type RAGFeedbackInput,
  type RAGEvaluationMetrics,
  type RetrievalResult,
  type RAGTestCase,
  type RAGTestResult,
  type FeedbackResult,
  // External knowledge functions
  syncDueSources,
  initGitHubIssuesConnector,
  registerConnector,
  type SyncAllResult,
  // Streaming updates functions
  handlePRMergeEvent,
  handleDocUpdateEvent,
  checkStaleness,
  markApproachingExpiry,
  cleanupExpired,
  refreshDiffChunk,
  refreshKnowledgeDoc,
  getStaleDocuments,
  type PRMergeEvent,
  type DocUpdateEvent,
  type StalenessResult,
  type CleanupResult,
  type TTLConfig,
  // Drift detection functions
  runTestSuite,
  generateDriftReport,
  checkMetricBounds,
  runDriftDetectionWithAlerts,
  type TestSuiteResult,
  type TestCaseResult,
  type DriftReport,
  type DriftMetricReport,
  type DriftAlert,
  type DriftDetectionWithAlertsResult,
  // Cost control functions
  getCachedEmbedding,
  cacheEmbedding,
  clearExpiredCache,
  clearCache,
  getCacheStats as getEmbeddingCacheStats,
  getCacheStats as getRAGCacheStats,
  setTenantTierConfig,
  getTenantTierConfig,
  selectEmbeddingTier,
  recordEmbeddingCost,
  recordQueryCost,
  shouldSkipExpensiveSearch,
  estimateEmbeddingCost,
  estimateMonthlyCost,
  recommendTier,
  // Budget-aware embedding functions
  generateBudgetAwareEmbedding,
  generateBatchBudgetAwareEmbeddings,
  BudgetExceededError,
  type TierSelectionResult,
  type CacheStats as EmbeddingCacheStats,
  type TenantTierConfig,
  type BudgetAwareEmbeddingOptions,
  type BatchBudgetAwareEmbeddingOptions,
  type BudgetAwareEmbeddingResult,
  type BatchBudgetAwareEmbeddingResult,
  // Multi-hop RAG functions
  traverseGraph,
  expandWithRelatedDocs,
  getGraphStats,
  findPath,
  type GraphNode,
  type MultiHopResult,
  type MultiHopOptions,
  // PR fix comment detection and ingestion
  analyzeComment,
  findFixComments,
  extractFixKnowledge,
  isDuplicateKnowledge,
  ingestPRFixComments,
  createFailureContext,
  type PRComment,
  type PRFixFailureContext,
  type FixCommentAnalysis,
  type ExtractedFixKnowledge,
  type IngestPRFixCommentsInput,
  type FixCommentIngestionResult,
  type IngestPRFixCommentsResult,
  // Slack resolution detection and ingestion
  detectResolution,
  hasResolutionSignals,
  ingestSlackResolution,
  batchIngestSlackResolutions,
  type SlackMessage,
  type SlackReaction,
  type SlackThread,
  type DetectedResolution,
  type ResolutionDetectionResult,
  type IngestSlackResolutionInput,
  type SlackResolutionFailureContext,
  type IngestSlackResolutionResult,
  type BatchIngestSlackResolutionsResult,
  // Analysis lesson ingestion
  ingestAnalysisLesson,
  extractAnalysisContext,
  type AnalysisLessonContext,
  type IngestAnalysisLessonResult,
  // Reranking
  rerankResults,
  applyHardRules,
  fullRerank,
  type RerankableResult,
  type QueryContext,
  type RerankedResult,
  type RerankOptions,
  // Linked commit ingestion (failure context + commit messages + diff)
  trackPRFailure,
  getPRFailures,
  clearPRFailures,
  ingestLinkedCommitKnowledge,
  createFailureSummary,
  type FailureSummary,
  type PRFailureContext,
  type LinkedCommitInput,
  type LinkedCommitResult,
  // Relationship detection for multi-hop RAG
  findRelatedDocuments,
  createDetectedRelationships,
  detectAndCreateRelationships,
  type DocumentContext,
  type DetectedRelationship,
  type RelationshipDetectionResult,
  // Test case seeding for drift detection
  seedTestCases,
  getSeedTestCaseTemplates,
  getSeedTemplatesByCategory,
  getSeedCategories,
  type SeedTestCasesResult,
} from "./rag/index.js";

// Fine-tuning
export {
  buildTrainingExample,
  toOpenAIFormat,
  toJSONL,
  filterExamples,
  calculateDatasetStats,
  logDatasetStats,
  type TrainingExample,
  type FeedbackQualityLabel,
  type TrainingExampleMetadata,
  type OpenAITrainingRow,
  type TrainingExampleInput,
  type DatasetStats,
  type DatasetBuildOptions,
} from "./finetuning/index.js";
export {
  registerModelVersion,
  getModelVersion,
  getAllModelVersions,
  getBaselineModel,
  updateFeatureFlags,
  getFeatureFlags,
  setTenantModelOverride,
  removeTenantModelOverride,
  triggerRollback,
  clearRollback,
  isRollbackActive,
  selectModel,
  logModelSelection,
  type ModelVersion,
  type ModelMetadata,
  type EvaluationMetrics,
  type ModelFeatureFlags,
  type ABTestConfig,
  type ModelSelectionResult,
  type ModelSelectionReason,
} from "./finetuning/index.js";
export {
  extractTrainingDataset,
  validateExtractedDataset,
  type ExtractionOptions,
  type ExtractionResult,
} from "./finetuning/index.js";
export {
  uploadTrainingFile,
  deleteTrainingFile,
  createFineTuningJob,
  getFineTuningJob,
  cancelFineTuningJob,
  listFineTuningJobs,
  waitForFineTuningJob,
  submitFineTuningWorkflow,
  type FineTuningJobOptions,
  type FineTuningJobResult,
  type FileUploadOptions,
  type FileUploadResult,
  type FineTuningWorkflowResult,
  type ProgressCallback,
} from "./finetuning/index.js";
