/**
 * Data Export Repository
 *
 * Database operations for data export job management (GDPR Article 20).
 *
 * @module database/dataExport/repository
 */

import { query, createLogger, getErrorMessage, validateNonEmptyString } from "../common.js";
import {
  DATA_EXPORT_QUERIES,
  DATA_EXPORT_STATUS,
  DATA_EXPORT_DEFAULTS,
} from "../../constants/dataExport.js";
import type {
  DataExport,
  DataExportRow,
  DataExportStatus,
  UpdateExportStatusInput,
} from "./types.js";

const logger = createLogger("data-export-repository");

// ==================== Row Mapper ====================

const mapRowToDataExport = (row: DataExportRow): DataExport => ({
  id: row.id,
  tenantId: row.tenant_id,
  status: row.status as DataExportStatus,
  requestedBy: row.requested_by,
  filePath: row.file_path,
  downloadUrl: row.download_url,
  expiresAt: row.expires_at,
  errorMessage: row.error_message,
  createdAt: row.created_at,
  completedAt: row.completed_at,
});

// ==================== Public API ====================

/**
 * Create a new data export job for a tenant.
 * ID is auto-generated by the database (gen_random_uuid).
 *
 * @param tenantId - Tenant requesting the export
 * @param requestedBy - User ID who requested the export
 * @returns The created export job
 */
export const createExportJob = async (
  tenantId: string,
  requestedBy: string
): Promise<DataExport> => {
  validateNonEmptyString(tenantId, "tenantId");
  validateNonEmptyString(requestedBy, "requestedBy");

  try {
    const result = await query<DataExportRow>(DATA_EXPORT_QUERIES.INSERT, [
      tenantId,
      DATA_EXPORT_STATUS.PENDING,
      requestedBy,
    ]);

    const exportJob = mapRowToDataExport(result.rows[0]);

    logger.info("Created data export job", { id: exportJob.id, tenantId });

    return exportJob;
  } catch (error) {
    logger.error("Failed to create data export job", {
      tenantId,
      error: getErrorMessage(error),
    });
    throw error;
  }
};

/**
 * Get a data export job by ID, scoped to tenant.
 *
 * @param id - Export job ID
 * @param tenantId - Tenant ID for isolation
 * @returns The export job or null if not found
 */
export const getExportJob = async (id: string, tenantId: string): Promise<DataExport | null> => {
  validateNonEmptyString(id, "id");
  validateNonEmptyString(tenantId, "tenantId");

  try {
    const result = await query<DataExportRow>(DATA_EXPORT_QUERIES.FIND_BY_ID, [id, tenantId]);
    return result.rows.length > 0 ? mapRowToDataExport(result.rows[0]) : null;
  } catch (error) {
    logger.error("Failed to get data export job", {
      id,
      tenantId,
      error: getErrorMessage(error),
    });
    throw error;
  }
};

/**
 * Update the status of an export job.
 *
 * @param input - Update parameters including optional file path, URL, and error
 * @returns The updated export job or null if not found
 */
export const updateExportStatus = async (
  input: UpdateExportStatusInput
): Promise<DataExport | null> => {
  validateNonEmptyString(input.id, "id");
  validateNonEmptyString(input.tenantId, "tenantId");

  try {
    const result = await query<DataExportRow>(DATA_EXPORT_QUERIES.UPDATE_STATUS, [
      input.status,
      input.filePath ?? null,
      input.downloadUrl ?? null,
      input.expiresAt ?? null,
      input.errorMessage ?? null,
      input.id,
      input.tenantId,
    ]);

    if (result.rows.length === 0) {
      return null;
    }

    logger.info("Updated data export status", {
      id: input.id,
      tenantId: input.tenantId,
      status: input.status,
    });

    return mapRowToDataExport(result.rows[0]);
  } catch (error) {
    logger.error("Failed to update data export status", {
      id: input.id,
      tenantId: input.tenantId,
      status: input.status,
      error: getErrorMessage(error),
    });
    throw error;
  }
};

/**
 * List export jobs for a tenant, most recent first.
 *
 * @param tenantId - Tenant ID
 * @param limit - Maximum results to return
 * @returns Array of export jobs
 */
export const listExportJobs = async (
  tenantId: string,
  limit: number = DATA_EXPORT_DEFAULTS.DEFAULT_LIST_LIMIT
): Promise<readonly DataExport[]> => {
  validateNonEmptyString(tenantId, "tenantId");

  try {
    const result = await query<DataExportRow>(DATA_EXPORT_QUERIES.LIST_BY_TENANT, [
      tenantId,
      limit,
    ]);
    return Object.freeze(result.rows.map(mapRowToDataExport));
  } catch (error) {
    logger.error("Failed to list export jobs", {
      tenantId,
      error: getErrorMessage(error),
    });
    throw error;
  }
};
