import {
  Siren,
  Activity,
  Cloud,
  BarChart3,
  Gauge,
  Triangle,
  Globe,
  Bug,
  Bell,
  LineChart,
  Train,
  Server,
} from "lucide-react";
import type { MonitoringProvider } from "./types";

/** Threshold: events received within the last 24 hours are considered "connected" */
export const STALE_MS = 24 * 60 * 60 * 1000;

export const MONITORING_PROVIDERS: readonly MonitoringProvider[] = [
  {
    id: "pagerduty",
    name: "PagerDuty",
    icon: Siren,
    active: true,
    webhookPath: "/webhooks/pagerduty",
    description:
      "Receive PagerDuty incident alerts with automatic severity classification and AI triage.",
    setupSteps: [
      "In PagerDuty, go to Integrations > Generic Webhooks (v3)",
      'Click "New Webhook"',
      "Paste the webhook URL shown above as the Endpoint URL",
      'Set the Scope to "Account" or select specific services',
      'Subscribe to "incident.triggered" events (at minimum)',
      "Copy the signing secret PagerDuty generates and set it as PAGERDUTY_WEBHOOK_SECRET in your Kenchi environment",
      "Save the webhook and trigger a test incident to verify alerts appear in Kenchi",
    ],
    requiredHeaders: ["x-webhook-id", "x-pagerduty-signature"],
  },
  {
    id: "datadog",
    name: "Datadog",
    icon: Activity,
    active: true,
    webhookPath: "/webhooks/datadog",
    description: "Datadog webhook integration for monitor alerts and event streams.",
    setupSteps: [
      "In Datadog, go to Integrations > Webhooks",
      'Click "New Webhook" and paste the webhook URL shown above',
      "Use the default JSON payload template with $ALERT_ID, $ALERT_TITLE, $ALERT_STATUS, $PRIORITY, $HOSTNAME, $TAGS",
      "Generate a shared secret and set it as DATADOG_WEBHOOK_SECRET in your Kenchi environment",
      "Configure monitors to include the header x-kenchi-webhook-secret with the same secret value",
      "Save and trigger a test monitor alert to verify",
    ],
    requiredHeaders: ["x-kenchi-webhook-secret"],
  },
  {
    id: "grafana",
    name: "Grafana",
    icon: Gauge,
    active: true,
    webhookPath: "/webhooks/grafana",
    description: "Grafana unified alerting webhook receiver with HMAC signature verification.",
    setupSteps: [
      "In Grafana, go to Alerting > Contact Points",
      'Create a new contact point with type "Webhook"',
      "Paste the webhook URL shown above",
      "Enable HMAC signature verification and set a webhook signing secret",
      "Set the same secret as GRAFANA_WEBHOOK_SECRET in your Kenchi environment",
      "Configure alert rules to use this contact point",
      "Trigger a test alert to verify",
    ],
    requiredHeaders: ["x-grafana-alerting-signature", "x-grafana-alerting-timestamp"],
  },
  {
    id: "prometheus",
    name: "Prometheus",
    icon: BarChart3,
    active: true,
    webhookPath: "/webhooks/prometheus",
    description: "Prometheus Alertmanager webhook receiver for firing alerts.",
    setupSteps: [
      "In your Alertmanager configuration (alertmanager.yml), add a webhook_configs entry",
      "Set the URL to the webhook URL shown above",
      "Add http_config headers with x-kenchi-webhook-secret set to your chosen secret",
      "Set the same secret as PROMETHEUS_WEBHOOK_SECRET in your Kenchi environment",
      "Reload Alertmanager configuration",
      "Trigger a test alert to verify",
    ],
    requiredHeaders: ["x-kenchi-webhook-secret"],
  },
  {
    id: "vercel",
    name: "Vercel",
    icon: Triangle,
    active: true,
    webhookPath: "/webhooks/vercel",
    description: "Vercel deployment failure and cancellation alerts via webhook.",
    setupSteps: [
      "In the Vercel Dashboard, go to Settings > Webhooks",
      'Click "Create Webhook" and paste the webhook URL shown above',
      "Select the deployment events to subscribe to (deployment.error, deployment.canceled)",
      "Copy the webhook signing secret Vercel generates",
      "Set the secret as VERCEL_WEBHOOK_SECRET in your Kenchi environment",
      "Save and trigger a failed deployment to verify",
    ],
    requiredHeaders: ["x-vercel-signature"],
  },
  {
    id: "netlify",
    name: "Netlify",
    icon: Globe,
    active: true,
    webhookPath: "/webhooks/netlify",
    description: "Netlify deploy failure alerts via webhook with JWS signature verification.",
    setupSteps: [
      "In the Netlify Dashboard, go to Site Settings > Build & Deploy > Deploy Notifications",
      'Click "Add notification" and choose "Outgoing webhook"',
      'Select the "Deploy failed" event',
      "Paste the webhook URL shown above",
      "Set a JWS secret and configure it as NETLIFY_WEBHOOK_SECRET in your Kenchi environment",
      "Save and trigger a failed deploy to verify",
    ],
    requiredHeaders: ["x-webhook-signature"],
  },
  {
    id: "sentry",
    name: "Sentry",
    icon: Bug,
    active: true,
    webhookPath: "/webhooks/sentry",
    description:
      "Sentry error and issue alerts with automatic stack trace extraction and AI root cause analysis.",
    setupSteps: [
      "In Sentry, go to Settings > Integrations > Internal Integrations",
      'Create a new integration or use "Webhooks" under Developer Settings',
      "Paste the webhook URL shown above as the Webhook URL",
      'Subscribe to "issue" events (issue.created at minimum)',
      "Copy the Client Secret and set it as SENTRY_WEBHOOK_SECRET in your Kenchi environment",
      "Optionally set SENTRY_API_TOKEN and SENTRY_ORGANIZATION_SLUG for enriched context fetching",
      "Save and trigger a test error to verify",
    ],
    requiredHeaders: ["sentry-hook-signature"],
  },
  {
    id: "opsgenie",
    name: "OpsGenie",
    icon: Bell,
    active: true,
    webhookPath: "/webhooks/opsgenie",
    description:
      "Atlassian OpsGenie alert lifecycle events with team routing and severity classification.",
    setupSteps: [
      "In OpsGenie, go to Settings > Integrations > Add Integration",
      'Select "Webhook" integration type',
      "Paste the webhook URL shown above",
      "Enable the alert actions you want to receive (Create, Acknowledge, Close)",
      "Set a webhook secret and configure it as OPSGENIE_WEBHOOK_SECRET in your Kenchi environment",
      "Optionally set OPSGENIE_API_KEY for enriched context fetching (alert details, notes, timeline)",
      "Save and trigger a test alert to verify",
    ],
    requiredHeaders: [],
  },
  {
    id: "newrelic",
    name: "New Relic",
    icon: LineChart,
    active: true,
    webhookPath: "/webhooks/newrelic",
    description: "New Relic alert policy notifications with NRQL-based context enrichment.",
    setupSteps: [
      "In New Relic, go to Alerts & AI > Notification Channels",
      'Create a new "Webhook" channel',
      "Paste the webhook URL shown above as the Base URL",
      "Set a custom header x-newrelic-webhook-secret with your chosen secret",
      "Set the same secret as NEWRELIC_WEBHOOK_SECRET in your Kenchi environment",
      "Optionally set NEWRELIC_API_KEY and NEWRELIC_ACCOUNT_ID for NerdGraph context enrichment",
      "Attach the channel to your alert policies and trigger a test to verify",
    ],
    requiredHeaders: ["x-newrelic-webhook-secret"],
  },
  {
    id: "railway",
    name: "Railway",
    icon: Train,
    active: true,
    webhookPath: "/webhooks/deploy/railway",
    description: "Railway deployment log analysis with real-time GraphQL subscription streaming.",
    setupSteps: [
      "In your Railway project, go to Settings > Webhooks",
      "Add a new webhook and paste the webhook URL shown above",
      "Select deployment events (deploy.started, deploy.completed, deploy.failed)",
      "Copy the signing secret and set it as RAILWAY_WEBHOOK_SECRET in your Kenchi environment",
      "Optionally set RAILWAY_API_TOKEN for REST log fetching as a fallback",
      "Deploy a change and verify Kenchi receives the event",
    ],
    requiredHeaders: ["x-railway-signature"],
  },
  {
    id: "render",
    name: "Render",
    icon: Server,
    active: true,
    webhookPath: "/webhooks/deploy/render",
    description: "Render deployment log analysis via REST polling with webhook-triggered fetching.",
    setupSteps: [
      "In the Render Dashboard, go to your service Settings > Notifications",
      'Add a webhook for "Deploy started" and "Deploy failed" events',
      "Paste the webhook URL shown above",
      "Set a signing secret and configure it as RENDER_WEBHOOK_SECRET in your Kenchi environment",
      "Optionally set RENDER_API_KEY for log fetching via the Render REST API",
      "Deploy a change and verify Kenchi receives the event",
    ],
    requiredHeaders: ["x-render-signature"],
  },
  {
    id: "cloudwatch",
    name: "CloudWatch",
    icon: Cloud,
    active: false,
    description: "AWS CloudWatch alarms via SNS subscription notifications.",
  },
];
