import { Siren, Activity, Cloud, BarChart3, Gauge, Triangle, Globe } from "lucide-react";
import type { MonitoringProvider } from "./types";

/** Threshold: events received within the last 24 hours are considered "connected" */
export const STALE_MS = 24 * 60 * 60 * 1000;

export const MONITORING_PROVIDERS: readonly MonitoringProvider[] = [
  {
    id: "pagerduty",
    name: "PagerDuty",
    icon: Siren,
    active: true,
    webhookPath: "/webhooks/pagerduty",
    description:
      "Receive PagerDuty incident alerts with automatic severity classification and AI triage.",
    setupSteps: [
      "In PagerDuty, go to Integrations > Generic Webhooks (v3)",
      'Click "New Webhook"',
      "Paste the webhook URL shown above as the Endpoint URL",
      'Set the Scope to "Account" or select specific services',
      'Subscribe to "incident.triggered" events (at minimum)',
      "Copy the signing secret PagerDuty generates and set it as PAGERDUTY_WEBHOOK_SECRET in your Kenchi environment",
      "Save the webhook and trigger a test incident to verify alerts appear in Kenchi",
    ],
    requiredHeaders: ["x-webhook-id", "x-pagerduty-signature"],
  },
  {
    id: "datadog",
    name: "Datadog",
    icon: Activity,
    active: true,
    webhookPath: "/webhooks/datadog",
    description: "Datadog webhook integration for monitor alerts and event streams.",
    setupSteps: [
      "In Datadog, go to Integrations > Webhooks",
      'Click "New Webhook" and paste the webhook URL shown above',
      "Use the default JSON payload template with $ALERT_ID, $ALERT_TITLE, $ALERT_STATUS, $PRIORITY, $HOSTNAME, $TAGS",
      "Generate a shared secret and set it as DATADOG_WEBHOOK_SECRET in your Kenchi environment",
      "Configure monitors to include the header x-kenchi-webhook-secret with the same secret value",
      "Save and trigger a test monitor alert to verify",
    ],
    requiredHeaders: ["x-kenchi-webhook-secret"],
  },
  {
    id: "grafana",
    name: "Grafana",
    icon: Gauge,
    active: true,
    webhookPath: "/webhooks/grafana",
    description: "Grafana unified alerting webhook receiver with HMAC signature verification.",
    setupSteps: [
      "In Grafana, go to Alerting > Contact Points",
      'Create a new contact point with type "Webhook"',
      "Paste the webhook URL shown above",
      "Enable HMAC signature verification and set a webhook signing secret",
      "Set the same secret as GRAFANA_WEBHOOK_SECRET in your Kenchi environment",
      "Configure alert rules to use this contact point",
      "Trigger a test alert to verify",
    ],
    requiredHeaders: ["x-grafana-alerting-signature", "x-grafana-alerting-timestamp"],
  },
  {
    id: "prometheus",
    name: "Prometheus",
    icon: BarChart3,
    active: true,
    webhookPath: "/webhooks/prometheus",
    description: "Prometheus Alertmanager webhook receiver for firing alerts.",
    setupSteps: [
      "In your Alertmanager configuration (alertmanager.yml), add a webhook_configs entry",
      "Set the URL to the webhook URL shown above",
      "Add http_config headers with x-kenchi-webhook-secret set to your chosen secret",
      "Set the same secret as PROMETHEUS_WEBHOOK_SECRET in your Kenchi environment",
      "Reload Alertmanager configuration",
      "Trigger a test alert to verify",
    ],
    requiredHeaders: ["x-kenchi-webhook-secret"],
  },
  {
    id: "vercel",
    name: "Vercel",
    icon: Triangle,
    active: true,
    webhookPath: "/webhooks/vercel",
    description: "Vercel deployment failure and cancellation alerts via webhook.",
    setupSteps: [
      "In the Vercel Dashboard, go to Settings > Webhooks",
      'Click "Create Webhook" and paste the webhook URL shown above',
      "Select the deployment events to subscribe to (deployment.error, deployment.canceled)",
      "Copy the webhook signing secret Vercel generates",
      "Set the secret as VERCEL_WEBHOOK_SECRET in your Kenchi environment",
      "Save and trigger a failed deployment to verify",
    ],
    requiredHeaders: ["x-vercel-signature"],
  },
  {
    id: "netlify",
    name: "Netlify",
    icon: Globe,
    active: true,
    webhookPath: "/webhooks/netlify",
    description: "Netlify deploy failure alerts via webhook with JWS signature verification.",
    setupSteps: [
      "In the Netlify Dashboard, go to Site Settings > Build & Deploy > Deploy Notifications",
      'Click "Add notification" and choose "Outgoing webhook"',
      'Select the "Deploy failed" event',
      "Paste the webhook URL shown above",
      "Set a JWS secret and configure it as NETLIFY_WEBHOOK_SECRET in your Kenchi environment",
      "Save and trigger a failed deploy to verify",
    ],
    requiredHeaders: ["x-webhook-signature"],
  },
  {
    id: "cloudwatch",
    name: "CloudWatch",
    icon: Cloud,
    active: false,
    description: "AWS CloudWatch alarms via SNS subscription notifications.",
  },
];
