export const SEGMENT_LABELS: Readonly<Record<string, string>> = {
  cicd: "CI/CD",
  failures: "Failures",
  analyses: "Analyses",
  pipelines: "Pipelines",
  incidents: "Incidents",
  active: "Active",
  timeline: "Timeline",
  postmortems: "Postmortems",
  infra: "Infrastructure",
  iac: "IaC Reviews",
  drift: "Drift",
  cost: "Cost",
  deployments: "Deployments",
  risk: "Risk Scores",
  rollouts: "Rollouts",
  analytics: "Analytics",
  integrations: "Integrations",
  settings: "Settings",
};
