/**
 * API Routes for n8n Integration
 *
 * Provides endpoints for n8n to interact with GitHub
 */

import { Router, type Request, type Response } from "express";
import { asyncHandler, createLogger, HTTP_STATUS, validate, validators } from "@kenchi/shared";
import { postPRComment } from "../services/githubService.js";
import { appConfig } from "../config/appConfig.js";

const router = Router();
const logger = createLogger("github-app");

/**
 * Format analysis into a GitHub comment
 */
const formatGitHubComment = (analysis: {
  summary: string;
  identified_cause?: string;
  confidence: number;
  recommended_actions?: Array<{ priority: string; description: string }>;
  repository: string;
}): string => {
  const confidencePercent = Math.round(analysis.confidence * 100);
  const confidenceLabel =
    analysis.confidence >= 0.8 ? "High" : analysis.confidence >= 0.5 ? "Medium" : "Low";

  let comment = `## 🔍 AI Analysis of CI Failure\n\n`;
  comment += `**Repository:** \`${analysis.repository}\`\n`;
  comment += `**Confidence:** ${confidenceLabel} (${confidencePercent}%)\n\n`;
  comment += `### Summary\n${analysis.summary}\n\n`;

  if (analysis.identified_cause) {
    comment += `### 🎯 Root Cause\n${analysis.identified_cause}\n\n`;
  }

  if (analysis.recommended_actions && analysis.recommended_actions.length > 0) {
    comment += `### 🛠️ Recommended Actions\n`;
    for (const action of analysis.recommended_actions) {
      const emoji =
        action.priority.toLowerCase() === "high"
          ? "🔴"
          : action.priority.toLowerCase() === "medium"
            ? "🟠"
            : "⚪";
      comment += `- ${emoji} **${action.priority}:** ${action.description}\n`;
    }
    comment += "\n";
  }

  comment += `---\n*🤖 Generated by Kenchi DevOps Assistant*`;

  return comment;
};

/**
 * POST /api/github/comment
 * Post a comment to a GitHub PR (called by n8n after analysis)
 */
router.post(
  "/api/github/comment",
  validate({
    body: {
      repository: (v) => validators.required(v) && validators.string(v),
      pr_number: (v) => validators.required(v) && typeof v === "number",
      analysis: (v) => validators.required(v) && typeof v === "object",
    },
  }),
  asyncHandler(async (req: Request, res: Response) => {
    const { repository, pr_number, analysis } = req.body;

    // Parse repository (owner/repo format)
    const [owner, repo] = repository.split("/");
    if (!owner || !repo) {
      res.status(HTTP_STATUS.BAD_REQUEST).json({
        error: "Invalid repository format. Expected 'owner/repo'",
      });
      return;
    }

    // Get installation ID from config
    const installationId = appConfig.github.installationId;
    if (!installationId) {
      logger.warn("No GitHub installation ID configured");
      res.status(HTTP_STATUS.BAD_REQUEST).json({
        error: "GitHub installation ID not configured",
      });
      return;
    }

    // Format the comment
    const comment = formatGitHubComment({
      summary: analysis.analysis || analysis.summary || "Analysis unavailable",
      identified_cause: analysis.identified_cause,
      confidence: analysis.confidence || 0.5,
      recommended_actions: analysis.recommended_actions,
      repository,
    });

    try {
      await postPRComment(installationId, owner, repo, pr_number, comment);

      logger.info("Posted analysis comment to GitHub PR", {
        repository,
        prNumber: pr_number,
      });

      res.status(HTTP_STATUS.OK).json({
        status: "posted",
        repository,
        pr_number,
      });
    } catch (error) {
      logger.error("Failed to post comment to GitHub", {
        repository,
        prNumber: pr_number,
        error: error instanceof Error ? error.message : "Unknown error",
      });

      res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).json({
        status: "error",
        error: error instanceof Error ? error.message : "Failed to post comment",
      });
    }
  })
);

export { router as apiRoutes };
